### ISSUE TITLE
sudo pip install git+git://github.com/saezlab/pypath.git failed in python 2 and 3

### ISSUE THREAD

**Issue by cebel** [saezlab/pypath#10]
Following traceback while in installation process in python 2 and 3

> Collecting git+git://github.com/saezlab/pypath.git
>   Cloning git://github.com/saezlab/pypath.git to /tmp/pip-9wm9jkkj-build
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-9wm9jkkj-build/setup.py", line 25, in <module>
>         common = imp.load_source('common', os.path.join('src', 'pypath', 'common.py'))
>       File "/usr/lib/python3.5/imp.py", line 172, in load_source
>         module = _load(spec)
>       File "<frozen importlib._bootstrap>", line 693, in _load
>       File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
>       File "<frozen importlib._bootstrap_external>", line 665, in exec_module
>       File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
>       File "src/pypath/common.py", line 18, in <module>
>         from future.utils import iteritems
>     ImportError: No module named 'future'

**Comment by deeenes** [comment]
@cebel thanks for catching this, fixed in 0.7.17
