### ISSUE TITLE
Typo in main.py source code

### ISSUE THREAD

**Issue by joanna-lada** [saezlab/pypath#100]
Hi Denes,
Thank you very much for this detailed response. After a bit more experimenting, I think I now get the distinction between neighborhood, 'affected_by/affects', 'stimulated/inhibits' etc with respect to the annotations available.

I think I have also spotted an error in src/pypath/main.py line 8559 onward:
```
    
def up_neighborhood(self, uniprot, order=1, mode='ALL'):
       
       if type(uniprots) in common.simpleTypes:
```

'pa.up_neighborhoods' returns the error

 if type(uniprots) in common.simpleTypes:
UnboundLocalError: local variable 'uniprots' referenced before assignment

Thanks again,

Joanna

_Originally posted by @joanna-lada in https://github.com/saezlab/pypath/issues/99#issuecomment-510844532_

**Comment by deeenes** [comment]
Fixed in f0e330f
