### ISSUE TITLE
SBML or SIF export?

### ISSUE THREAD

**Issue by luli7** [saezlab/pypath#101]
Hi Everyone,

I wonder whether there is some functions in pypath for exporting network to SBML, or SIF, which can keep the attributes (of edges)?

Thank you for your answer
Best regards
Lu

**Comment by deeenes** [comment]
Hi Lu,

There are a couple of methods for export:

```
from pypath import main, data_formats

pa = pypath.PyPath()
pa.init_network(data_formats.pathway)

# due to limitations of the SIF format it keeps only the direction and sign attributes:
pa.export_sif(outfile = 'pathway.sif')

# graphviz dot format (with many options):
pa.export_dot(save_dot = 'pathway.dot')

# tsv tables:
pa.export_tab(outfile = 'pathway.tsv')
# an alternative format:
pa.export_tab(outfile = 'pathway0.tsv', unique_pairs = False)
```

We don't have `SBML` export. Do you think it would be useful? Would it be difficult to implement?

Best,

Denes

**Comment by luli7** [comment]
Dear Denes,

Thank you very much for your reply.
I do not think converting Omnipath to SBML would be difficult. However, to reserve the vast amount annotation in a meaningful and searchable way, SBML might not be a good choice. But on the other hand, to bring Omnipath to wider community, I guess people would like to have a SBML or BioPAX export.

I think some of you are in COMBINE, that might be a better place to discuss.

Thank you again!
Lu

**Comment by deeenes** [comment]
Hi Lu,

Thanks for the suggestion, I agree it would be nice to have these.
Unfortunately we were not at combine (you mean the conference last week?).
But of course we can discuss other ways.

Best,

Denes

**Comment by luli7** [comment]
Hi Denes and Nic,

Sorry to come back to this again.
I wonder is there a way to convert igraph object (generated by pypath) to sif or text, other than from the pypath object (as you shown above).

The reason is that I derived a directed sub-network from omnipath for my gene list, and trimmed the unconnected nodes. I would like to view it in cytoscape, as the network is quite big and the layout and clustering algorithms are relatively limited in igraph (I am very new to igraph so this conclusion might be wrong, feel free to give me suggestions.). I thought the quickest way is to convert this network to sif and visualize/clustering it in cytoscape. However I can not easily export igraph to sif while still maintaining the nodes' name (other than use index as in igraph).

Thank you for your help as always.
Best regards
Lu

**Comment by deeenes** [comment]
Hi Lu,

Yes `igraph` has many export methods. Just look at them by `graph.write...` and hit <tab>.
There is for example the `igraph.Graph.write_edgelist` and `igraph.Graph.write_ncol`.
I think these probably can be adapted to your needs.

At the same time I think `igraph` is also good in layouts and community detection algorithms.
For plotting a large network I would recommend the `layout_fruchterman_reingold` with good parameters, like for example these: https://bitbucket.org/snippets/deeenes/LjL5R/good-fruchterman-reingold-layout
Community detection methods you can try all of them except some which will be too slow on huge networks. The `community_fastgreedy` for example used to give fairly good results and is very quick. The `community_spinglass` is also good but too slow for large graphs.

I hope this helps.

Best wishes,

Denes
