### ISSUE TITLE
Unable to save the network to the specified file

### ISSUE THREAD

**Issue by glmanhtu** [saezlab/pypath#102]
Hello,

I'm trying to save the network into a custom file but it seem to me that it didn't work. I have digged in the source code and found that you haven't passed the pfile into the save_network() function

https://github.com/saezlab/pypath/blob/master/src/pypath/main.py#L1647

**Comment by deeenes** [comment]
Hi,

Thanks a lot, should be fixed on `dev` by 41ed830

Best,

Denes
