### ISSUE TITLE
igraph plot the directed graph

### ISSUE THREAD

**Issue by luli7** [saezlab/pypath#103]
Hi Denes and Nick,

I am not sure this is the best place to pose this question. But just in case you have an answer.
I am trying to plot a sub-network obtained from Omnipath (the core Omnipath with direction).
I am trying to colour the edge based on 'stimulation' or 'inhibition', as following.
My question is, how to colour the reverse direction....how bi-directional interaction edge counted in igraph?

from itertools import compress
''''
edgecolor_dic={'stimulation':'red','inhibition':'blue','NA':'black'}
choice=['stimulation','inhibition']

plot=igraph.plot(subgraph,target='subnetwork.png', edge_color=[edgecolor_dic[list(compress(choice,d.get_sign(d.straight)))[0] if list(compress(choice,d.get_sign(d.straight))) else 'NA'] for d in subgraph.es['dirs']]) 

as you can see above, here I am only judge 'straight' direction and combine with the Boolean value of 'stimulation' or 'inhibition' to colour the edge. I am not sure how can I colour the 'reverse' direction?

Thank you very much in advance.
Best regards
Lu

**Comment by deeenes** [comment]
Hi Lu,

Here is an example I think exactly for your question:
https://github.com/saezlab/pypath/issues/99#issuecomment-510160282

Briefly, for `igraph.plot` it is convenient to convert the network to a directed `igraph.Graph` object, then the coloring is trivial.

Best,

Denes
