### ISSUE TITLE
MacOS catalina

### ISSUE THREAD

**Issue by FabianRup** [saezlab/pypath#117]
Hey Omnipath team, 

is there information about installation of pypath on Catalina?
I just tried the installation via anaconda but it didn't work at all. 

Best
Fabian

**Comment by deeenes** [comment]
Hi Fabian,

To have a chance to help with this we need to find a specific error message and find out which packages failed to install. I would recommend to open the conda install shell script of pypath and execute each installation step manually in the terminal and watch out for error messages. Even before that you could open a Python shell and check which modules are missing (importing igraph, cairo, etc.) 

Best,

Denes

**Comment by FabianRup** [comment]
Dear Denes, 

I will try to locally install pypath step by step soon and will come back to you.

Until then, maybe you can help with a more specific problem (maybe I can also use the web service):
I have a list of about 50 candidate proteins that probably play a role in a signalling pathway. However, this proteins can act in probably any way possible (Protein-Protein-Interaction, Protein-Small molecule interaction, change in localisation, etc. etc.). Therefore I want to use Omnipaths combined database power (Interactions, Go-Terms, etc.) to search for 'missing links' in between these candidate proteins to maybe come up with a possible pathway of interaction. 
Is there a way to query for such 'missing links' in a set of proteins?

Thanks and best wishes
Fabian

**Comment by Nic-Nic** [comment]
Dear Fabian,

If you're using `pypath`, you can use of any of the functions that `igraph` provides to find paths between any two given nodes (there are several options, see the documentation [here](https://igraph.org/python/doc/igraph.GraphBase-class.html)).

For example, once you initialize the network with:
```python
from pypath.main import PyPath

pa = PyPath()
pa.init_network()
```
You can find all shortest paths between two given nodes (let's say from `v1` to `v2`) with:
```python
pa.graph.get_all_shortest_paths(v1, to=v2)
```
Best,
Nico

**Comment by deeenes** [comment]
Hi Fabian,

I would add some more relevant points:

Besides `igraph.graph.get_all_shortest_paths`, `pypath.main.PyPath` provides a more flexible method for searching paths, it's called `find_all_paths`.

In the pypath guide you can see an example how to query Gene Ontology:
http://pypath.omnipathdb.org/notebooks/pypath_guide.html#gene-ontology

The pathway memberships and many other characteristics of the proteins are accessible in the `pypath.annot` module:
http://pypath.omnipathdb.org/notebooks/pypath_guide.html#annotations

The annotation and the GO annotation objects provide many methods for various queries.

You might find useful also the methods of the `PyPath` object for querying causality:

http://pypath.omnipathdb.org/notebooks/pypath_guide.html#causality

If you choose to use the web service, all interactions and annotations are available there, and we have also an R package which brings the data for you in R:

https://github.com/saezlab/OmnipathR

I hope it helps, please let us know if you have more questions.

Best,

Denes
