### ISSUE TITLE
Error when querying web service for references in JSON format

### ISSUE THREAD

**Issue by johnbachman** [saezlab/pypath#120]
When I query the omnipathdb.org web service for ptms with sources and references, it works:

http://omnipathdb.org/ptms/?fields=sources,references

But when I query for the same info in JSON format I get an error message:

http://omnipathdb.org/ptms/?format=json&fields=sources,references

If I drop references from the query but keep sources, it works with JSON:

http://omnipathdb.org/ptms/?format=json&fields=sources

We'd like to get the info with references in JSON format. Any help would be appreciated!

**Comment by deeenes** [comment]
Hi John,

Thank you for reporting this! Fixed in d119bc3, the server should be updated soon.

Best,

Denes
