### ISSUE TITLE
uniprot - downloading sec_ac.txt failed - 'NoneType' object not iterable

### ISSUE THREAD

**Issue by Chrizsly** [saezlab/pypath#121]
Hi,
I am trying to run the following code:

`pa = main.PyPath()
pa.init_network({'signor': data_formats.pathway['signor']})`

with the following log messages:

> Downloading `download_entity.php` from signor.uniroma2.it -- 0.00B downloaded: : 10.7Mit [00:03, 3.21Mit/s]
        Downloading `` from www.uniprot.org -- 0.00B downloaded: : 1.53Mit [14:48, 1.72kit/s]
        Downloading `sec_ac.txt` from ftp.uniprot.org -- failed: : 0.00it [00:01, ?it/s]

finally getting this error

> TypeError: 'NoneType' object is not iterable

I already checked the closed issues here, downloaded the most recent version of pypath (0.8.48), cleared the cache in pypath. The dowloading was running ~ 5 min when it stopped with the error (before clearing cache it stopped after ~ seconds).

The error seems to happen in "mapping_input.py", line 61
`if organism is not None:
        proteome = uniprot_input.all_uniprots(organism=organism)
        proteome = set(proteome)
    sec_pri = []
    url = urls.urls['uniprot_sec']['url']
    c = curl.Curl(url, silent = False, large = True, timeout = 2400)
    
    for line in filter(
        lambda line:
            len(line) == 2 and (organism is None or line[1] in proteome),
            map(
                lambda i:
                    i[1].split(),
                filter(
                    lambda i: i[0] >= 30,
                    enumerate(c.result)
                )
            )
        ):`

Any help would be really appreciated :) 

Thanks!

**Comment by Chrizsly** [comment]
It appears that the URL generated in 'mapping_input.py' is wrong. Searching for the 'sec_ac.txt' file online results in this URL:

> ftp://ftp.uniprot.org/pub/databases/uniprot/knowledgebase/docs/sec_ac.txt

while the aforementioned file generates this URL:

> ftp://ftp.uniprot.org/pub/databases/uniprot/knowledgebase/complete/docs/sec_ac.txt


So, for now, I hardcoded the URL and the download of the Signor network was successful. An update in the code would be nice though!

**Comment by Nic-Nic** [comment]
Many thanks for pointing this out. It's bee fixed in b81e88e (`dev` branch).
They changed the URL and now is:
ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/docs/sec_ac.txt
