### ISSUE TITLE
load_omnipath - charmap - encoding \u01a1 - can't decode

### ISSUE THREAD

**Issue by Chrizsly** [saezlab/pypath#122]
Hi,

I am running the following code: 
`pa.load_omnipath()`

returning the following error message:
> Traceback (most recent call last):
> 
>   File "<ipython-input-6-31b77a95ab57>", line 1, in <module>
>     pa.load_omnipath()
> 
>   File "C:\Users\cmaass\AppData\Local\Continuum\anaconda3\lib\site-packages\pypath\main.py", line 13099, in load_omnipath
>     self.load_resources(omnipath, exclude = exclude)
> 
>   File "C:\Users\cmaass\AppData\Local\Continuum\anaconda3\lib\site-packages\pypath\main.py", line 6312, in load_resources
>     keep_raw = keep_raw,
> 
>   File "C:\Users\cmaass\AppData\Local\Continuum\anaconda3\lib\site-packages\pypath\main.py", line 6382, in load_resource
>     keep_raw = keep_raw,
> 
>   File "C:\Users\cmaass\AppData\Local\Continuum\anaconda3\lib\site-packages\pypath\main.py", line 2541, in read_data_file
>     self._log(str(e.args))
> 
>   File "C:\Users\cmaass\AppData\Local\Continuum\anaconda3\lib\site-packages\pypath\session_mod.py", line 79, in _log
>     self._logger.msg(msg = msg, label = self._log_name, level = level)
> 
>   File "C:\Users\cmaass\AppData\Local\Continuum\anaconda3\lib\site-packages\pypath\log.py", line 153, in msg
>     self.fp.write(msg)
> 
>   File "C:\Users\cmaass\AppData\Local\Continuum\anaconda3\lib\encodings\cp1252.py", line 19, in encode
>     return codecs.charmap_encode(input,self.errors,encoding_table)[0]
> 
> UnicodeEncodeError: 'charmap' codec can't encode character '\u01a1' in position 162: character maps to <undefined>
> 

problem seems with encoding and utf-8. I am not sure where/how this would need to be updated in order to run...

Thanks for the help!

**Comment by Nic-Nic** [comment]
Not 100% sure but may be related to default encoder on Windows.
I just specified the encoder for the logger in 1a0a095 to UTF-8.
Could you please try if it works now?

**Comment by Chrizsly** [comment]
Nope, not working. I copied the file and tried to re-run, same error

**Comment by Nic-Nic** [comment]
I tried to reproduce in Linux and Mac with empty cache and couldn't reproduce the error... Seems to be Windows-specific. I'll try to investigate what's going on.

**Comment by deeenes** [comment]
Hi Chrizsly,

We can not reproduce this on Linux, so we can only guess, but maybe this helps: 8c8c5b6
Also for quicker testing, you can use the lines below (also before and after installing the update in 8c8c5b6):

```
import pypath
pypath.session_mod.get_logger().msg('this is the trouble maker: ơ ')
```

Best,

Denes

**Comment by Chrizsly** [comment]
Hi,

thanks for the help - but the suggested changes are not solving the problem. Also, I cant run the second line of code, 'no attribute get_logger'. 
I re-installed from the last update

**Comment by deeenes** [comment]
Sorry, it's `get_log`.
Also what happens if you run this code:

```
fp = open('testfile.txt', 'wb')
fp.write('foo ơ bar'.encode('utf8'))
```

**Comment by Nic-Nic** [comment]
There was a bug in my last commit (5deb0eb) it works now (88e3463)

**Comment by deeenes** [comment]
Nico also added `errors = 'replace'` to the `encode` method, have you tried that?

**Comment by Chrizsly** [comment]
`fp = open('testfile.txt', 'wb')
fp.write('foo ơ bar'.encode('utf8'))`

output: 10

tried the recent updates, not working...
just to check: under 'dev', when I copy the git URL and use pip install git+URL, this should update everything, right?

**Comment by Nic-Nic** [comment]
- Not sure if synonyms, but the encoding argument should be `'utf-8'` (with a hyphen)
- The `10` is the return of the function `fp.write()`, do `fp.close()` and see what's written in the `testfile.txt`, for me it worked.
- Regarding `pip install git+URL`, yes it should re-install. If you want to make sure, you can always use the flags `--upgrade` or `--force-reinstall`

**Comment by Chrizsly** [comment]
still no progress.

**Comment by deeenes** [comment]
Are you sure you are installing from the `dev` branch?

```
pip install https://github.com/saezlab/pypath/archive/dev.zip
```

That's weird because the minimal example above worked for you and we do exactly the same in the module.

**Comment by Chrizsly** [comment]
problem solved! it worked now! Downloading the Omnipath DB took ~ 30 min. Thanks a lot!

**Comment by deeenes** [comment]
Great, 30 min is a good time ;)
Subsequent runs will load the data from the local cache hence it will be faster.
But you can always save the network into a `pickle`, then loading takes less than a minute:

```
pa.save_to_pickle('mynetwork.pickle')

# and to load

pa = pypath.main.PyPath()
pa.load_from_pickle(pickle_file = 'mynetwork.pickle')
```
