### ISSUE TITLE
Segfault when performing load_resources()

### ISSUE THREAD

**Issue by wariobrega** [saezlab/pypath#123]
I keep having a segmentation fault error when downloading the pypath database

**To Reproduce**
1. create an empty conda environment (tried with different environments)
2. install pypath using the pip command on the website
3. followed tutorial 1 or 3  to load resources 

**Desktop**
 - Ubuntu server
- Python version: 3.6.4 
- Pypath Version  v0.8.3

![Screenshot from 2019-11-19 17-22-07](https://user-images.githubusercontent.com/10073781/69165312-a895b100-0af1-11ea-8ffe-ee538231eeec.png)

**Comment by deeenes** [comment]
Hi,

I think anything what causes segfault might be only related to binary libraries and pretty much out of our control. As no one else experienced this segfault so far, it's probably related to the specific versions and compilation parameters of the packages from your Linux and Python distribution.

Still it would be interesting to see where this segfault happens, you could run with `gdb` as you see for example here: https://stackoverflow.com/q/16731115/854988
Maybe from the trace we will know more how to address it.

I think the easiest if first you could try with an up-to-date Python (3.8.0 is the current release) and it will also bring you the necessity to install all the necessary packages again (including `pypath`, current version is 0.8.50). This might be matter of luck but I expect it will resolve the issue.

If that does not work next would be to try another Linux (or the same but all packages updated).

Please keep us posted.

Best,

Denes

**Comment by wariobrega** [comment]
Dear Denes,

Thanks for your quick reply.

I created an empty conda env with python 3.8 and after several attempts, I managed to install pypath

Please note that I had to install also `numpy scipy` and `statsmodels` other than the other dependencies listed on the main website in the conda environment. Is it a known issue?

I did, however, encounter another major problem, which regards the file download with the `load_omnipath()` module. I attach here a screenshot of log report, Apparently, there is a problem in downloading the databases. I tried to replicate the issue on two different machines running Ubuntu Server 16.04 and Linux Mint 19, and on two different networks, but the error is the same.

Maybe there's a problem in some of the database URLs or the way the0re accessed? 

Thank you for your help!
![Screenshot from 2019-11-20 11-55-36](https://user-images.githubusercontent.com/10073781/69233665-9a956e00-0b8d-11ea-81f9-bcabfdc9d064.png)

Daniele

**Comment by Nic-Nic** [comment]
This issue with UniProt URL was solved in #121 
Could you try installing the PyPath version from the tip of the `dev` branch and try again?

**Comment by deeenes** [comment]
Thanks for  reporting about missing dependencies. I would assume `pip` in conda would install these automatically, does it? Or you got some error at the first import?

**Comment by wariobrega** [comment]
@Nic-Nic Thanks, I will try to install the dev branch now!

@deeenes I thought the same, but actually the conda `pip` seems to ignore the automatic download of these dependencies and just skips to the installation of pypath
I will list here the commands I ran in order for you to reproduce the issue and confirm it:
1. `conda create -n omnipath python=3.8`
2. `conda install -c conda-forge -y python-igraph graphviz cairo pycairo pygraphviz`
3. `pip install git+git://github.com/saezlab/pypath.git`
 
**Note** also that the statsmodel dependency MUST be downloaded from conda-forge and not from the canonical anaconda, as the version in the anaconda distribution gives a conflict error when downloading.

Hope this will help!

Daniele

**Comment by wariobrega** [comment]
@Nic-Nic  I can confirm that the `load()` function in the `dev` branch now works correctly (tried importing SIGNOR and, as far as I understood, the data is there (i can load the corresponding graph and it seems populated, as the screenshot suggests.
![Screenshot from 2019-11-20 15-22-00](https://user-images.githubusercontent.com/10073781/69246732-8eb7a500-0ba9-11ea-822f-1c71bc3cf430.png)

I have to notice you, however, that the pa.load() prints nothing to screen, even when downloading all the resources the first time. I don't know if this is expected (maybe I am missing a verbose flag?) but in the `master` branch "version" the command seemed more informative!

Anyways, thanks a lot for your help!

**Comment by deeenes** [comment]
@wariobrega Great, indeed the network has been loaded. You can follow the log messages in the log file (I think the path printed when you import `pypath` or you can find by `pypath.session_mod.get_log().fname`. If you want to print messages to the console, you need to increase the log level dispatched to the console:

```
pypath.session_mod.get_log().console_level = 5
```

**Comment by wariobrega** [comment]
Thanks!
