### ISSUE TITLE
API status and documentation

### ISSUE THREAD

**Issue by sigven** [saezlab/pypath#124]
Thanks for a very comprehensive and useful resource!

I tried your API (omnipathdb.org), and found a number of useful annotations. I have a few comments for which I would very much appreciate some feedback:

* It is occasionally hard to understand what the underlying source is. In particular, I noticed the `CPAD` source, which gives specific annotations as to how the protein is implicated in dedicated cancer pathways etc. From your long list of sources, and from the abbreviation, I reckoned this came from the ConsensusPathDB, but I could not see how this type of information is present here. Do you have any explanation for this?

* It would be very helpful to also list the version/release of each source when retrieving data from the API (i.e. in order to understand how old/fresh each knowledge resource is), and to ensure reproducibility of any analysis undertaken

* For protein complexes, the information retrieved through the API seems currently to be lacking in many instances. Your example query supposedly shows all complexes in which MTOR is participating:
   http://omnipathdb.org/complexes?proteins=P42345&databases=CORUM,PDB

   I seem to recall that the resultset was much longer previously(?); and I believe this can be confirmed when searching for MTOR directly in CORUM (https://mips.helmholtz-muenchen.de/corum/). Any comments to this?

If there is an update in the making, it would be helpful to know when this is completed, as I want to utilize your API in other tools/workflows. I also noticed that the documentation wrt the signalling resources is not responding currently (http://omnipathdb.org/info)

kind regards,
Sigve

**Comment by deeenes** [comment]
Hi Sigve,

Thank you for the very helpful feedback!

> Thanks for a very comprehensive and useful resource!
> 
> I tried your API (omnipathdb.org), and found a number of useful annotations. I have a few comments for which I would very much appreciate some feedback:
> 
>     * It is occasionally hard to understand what the underlying source is. In particular, I noticed the `CPAD` source, which gives specific annotations as to how the protein is implicated in dedicated cancer pathways etc. From your long list of sources, and from the abbreviation, I reckoned this came from the ConsensusPathDB, but I could not see how this type of information is present here. Do you have any explanation for this?
> 
>     * It would be very helpful to also list the version/release of each source when retrieving data from the API (i.e. in order to understand how old/fresh each knowledge resource is), and to ensure reproducibility of any analysis undertaken

We are aware of these issues and already working on standardizing the resource names and the handling of all their meta-information in the `pypath` module (#116 aims to address one part of this). When finish this work in the web service the download date and URL will be accessible for all the original resources. In addition in the http://omnipathdb.org/info page more up-to-date and information will be available for all the resources (now many of them are missing, as we updated this page long time ago).

> 
>     * For protein complexes, the information retrieved through the API seems currently to be lacking in many instances. Your example query supposedly shows all complexes in which MTOR is participating:
>       http://omnipathdb.org/complexes?proteins=P42345&databases=CORUM,PDB
>       I seem to recall that the resultset was much longer previously(?); and I believe this can be confirmed when searching for MTOR directly in CORUM (https://mips.helmholtz-muenchen.de/corum/). Any comments to this?

Thanks for reporting this, it was a bug, I fixed in 3d76815, now it's possible to search by protein again.

> 
> 
> If there is an update in the making, it would be helpful to know when this is completed, as I want to utilize your API in other tools/workflows. I also noticed that the documentation wrt the signalling resources is not responding currently (http://omnipathdb.org/info)

Also a bug in `pypath`, now fixed.

ps. sorry for not answering your email, the forwarding wasn't set up correctly, we fixed that too.

Best wishes,

Denes 

> 
> kind regards,
> Sigve

**Comment by sigven** [comment]
Thanks a lot for the comprehensive feedback :-)

**Comment by deeenes** [comment]
No problem, thanks for using pypath/OmniPath :)
