### ISSUE TITLE
broken example

### ISSUE THREAD

**Issue by ACMGlueck** [saezlab/pypath#126]
The Human Protein Atlas example you are giving on your main page, with the http://omnipathdb.org/annotations?databases=HPA&proteins=BMP7 link, is unfortunately broken.

**Comment by deeenes** [comment]
Hi Anton,

Thanks for catching this, fixed in 62092e2

As now we have both tissue and subcellular annotations from HPA, the URL looks like:
http://omnipathdb.org/annotations?databases=HPA_tissue,HPA_subcellular&proteins=BMP7

Best,

Denes

**Comment by ACMGlueck** [comment]
Hi Denes,

Excellent!  Thanks for the quick reaction and fix,

best regards,

Anton
