### ISSUE TITLE
'NetworkInput' object has no attribute 'networkinput'

### ISSUE THREAD

**Issue by ntung** [saezlab/pypath#131]
**Describe the bug**
'NetworkInput' object has no attribute 'networkinput'

**To Reproduce**
Running the simple snippet below:
`
from pypath import main
from pypath import data_formats
pa = main.PyPath()
pa.load_resources({'signor': data_formats.pathway['signor']})
`
This snippet was extracted from [the notebook guide](http://pypath.omnipathdb.org/notebooks/pypath_guide.html)

**Expected behaviour**
I am not entirely sure what will happen if this code gets through.

**Traceback**
If you have a traceback please quote it in your report.

**Logfile**
Please attach the log file or at least the last few lines of it.
This way we can see better exactly at which operation and at
processing of which dataset the error occurred.

**Desktop (please complete the following information):**
 - OS: MacOS Catalina, version 10.15.3
 - Python version: [e.g. 3.7.6_1]
 - Version: v0.9.6

**Additional context**
Below is the full stacktrace:
`
>>> from pypath import main

	=== d i s c l a i m e r ===

	All data accessed through this module,
	either as redistributed copy or downloaded using the
	programmatic interfaces included in the present module,
	are free to use at least for academic research or
	education purposes.
	Please be aware of the licenses of all the datasets
	you use in your analysis, and please give appropriate
	credits for the original sources when you publish your
	results. To find out more about data sources please
	look at `pypath.descriptions` or
	http://omnipathdb.org/info and
	`pypath.data_formats.urls`.

[2020-02-20 10:24:53] [pypath]
	- session ID: `zld54`
	- working directory: `/Users/tnguyen/syncs/learnpython/pypath_0.9.6`
	- logfile: `/Users/tnguyen/syncs/learnpython/pypath_0.9.6/pypath_log/pypath-zld54.log`
	- pypath version: 0.9.6
[2020-02-20 10:24:55] [curl] Module `pysftp` not available. Only downloading of a small number of resources relies on this module. Please install by PIP if it is necessary for you.
[2020-02-20 10:24:56] [dataio] Module `bioservices` not available.
>>> from pypath import settings
>>> pa = main.PyPath()
>>> pa.load_resources({'signor': data_formats.pathway['signor']})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'data_formats' is not defined
>>> from pypath import data_formats
>>> pa.load_resources({'signor': data_formats.pathway['signor']})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tnguyen/syncs/learnpython/pypath_0.9.6/lib/python3.7/site-packages/pypath/main.py", line 6557, in load_resources
    for k, v in iteritems(lst)
  File "/Users/tnguyen/syncs/learnpython/pypath_0.9.6/lib/python3.7/site-packages/pypath/main.py", line 6561, in <genexpr>
    v.networkinput.huge
AttributeError: 'NetworkInput' object has no attribute 'networkinput'
>>>
`

**Comment by deeenes** [comment]
Hi Tung,

Thanks a lot for reporting this, fixed in 36a9405

Best,

Denes

**Comment by deeenes** [comment]
Of note, the pypath guide notebook needs a major update, we are lagging behind with it, apologies about that. Please take a look at the top of the repository readme.

**Comment by ntung** [comment]
> Of note, the pypath guide notebook needs a major update, we are lagging behind with it, apologies about that. Please take a look at the top of the repository readme.

I used to raise the issue of updating the documentation more often.

On a different note, I am trying to digging out the source code. There are some bugs preventing me from running tests. I will update in another issue.

**Comment by deeenes** [comment]
You are completely right, that time we updated the docs, but we keep that issue open as this week we merged a major reorganization of the module and few weeks ago the new network API which requires a complete revision of the guide notebook, it is in progress.

Which tests do you mean? The tests in the module are unfortunately very incomplete and outdated. We will add new tests at some point.

Otherwise we appreciate really much you are using pypath and open issues, these help us a lot!
