### ISSUE TITLE
Apply programming styles

### ISSUE THREAD

**Issue by ntung** [saezlab/pypath#136]
Hi all,

I am digging out the source. The first impression on me is that there are some super long methods. For example:
`pypath.legacy.main.orthology_translation`
lengths over 450 lines.
I guess this package will be get rid of in next iterations as its name reveals.

There are a lot of unnecessary blank lines between method signature and its body. I found many typos and unusal variable names. Pay attention to typos in variables and methods names also docs.

Some variables are CamelCase style, e.g. `readError, thisSign, thisSources`...

In my point of view, collaborative team should respect some guidelines and best pratices for easing review code, maintainability and readibility in term of software engineering perspective. Also it is better to reuse a piece of code.

Recommend: Using PyCharm is genuienly handy for refactoring all sorts of above concerns. The IDE recommends programmers how and where to refactor.

It is not recommended to access a protected member out of class unless it is in sub-classes. When you define `get_log` as a public method, why don't you use it instead of `_logger._log`?.

Best regards,
Tung

**Comment by Nic-Nic** [comment]
Hi Tung,

> Hi all,
> 
> I am digging out the source. The first impression on me is that there are some super long methods. For example:
> `pypath.legacy.main.orthology_translation`
> lengths over 450 lines.
> I guess this package will be get rid of in next iterations as its name reveals.

That's correct

> There are a lot of unnecessary blank lines between method signature and its body. I found many typos and unusal variable names. Pay attention to typos in variables and methods names also docs.

Not sure what you mean by "unnecessary blank lines" or "unusual variable names". Regarding typos, we try to fix them as soon as they're spotted, you're welcome to open an issue or PR if you find one.

> Some variables are CamelCase style, e.g. `readError, thisSign, thisSources`...

Guess you mean mixedCase and I don't see a problem here, this is not in conflict with PEP8

> In my point of view, collaborative team should respect some guidelines and best pratices for easing review code, maintainability and readibility in term of software engineering perspective. Also it is better to reuse a piece of code.

We are aware of this and are currently working on this in the current refactoring

> Recommend: Using PyCharm is genuienly handy for refactoring all sorts of above concerns. The IDE recommends programmers how and where to refactor.

Thanks for the recommendation

> It is not recommended to access a protected member out of class unless it is in sub-classes. When you define `get_log` as a public method, why don't you use it instead of `_logger._log`?.

Good point, we'll take it into consideration @deeenes 

> Best regards,
> Tung

Cheers

**Comment by ntung** [comment]
Hi @Nic-Nic,

You could mix different styles if you like. However, as the big project, we should make this consitent. The more we mess up, the more difficult we can handle and maintain.

About a lot of extra blank line after you define method signature. Let's say:

```
    def flush(self):
        """
        Flushes the log file.
        """

        if hasattr(self, 'fp') and not self.fp.closed:

            self.fp.flush()
```
The method aims to flush messages to the file. How many do we have? We can easily find such  spare blank lines.

Below are the other examples.

<img width="425" alt="Screenshot 2020-02-21 at 13 24 07" src="https://user-images.githubusercontent.com/663341/75038132-a9056580-54ad-11ea-8c88-79cc063ac292.png">

<img width="524" alt="Screenshot 2020-02-21 at 13 24 19" src="https://user-images.githubusercontent.com/663341/75038141-adca1980-54ad-11ea-9e17-79018cb7191a.png">

<img width="325" alt="Screenshot 2020-02-21 at 13 24 40" src="https://user-images.githubusercontent.com/663341/75038151-b15da080-54ad-11ea-93f4-5a75a4efde5c.png">

<img width="436" alt="Screenshot 2020-02-21 at 13 25 19" src="https://user-images.githubusercontent.com/663341/75038157-b4f12780-54ad-11ea-8841-a8ffbf0af746.png">

I am working on refactoring these. Hopefully, there will have been a pull request today.

Regards,
Tung

**Comment by ntung** [comment]
What do you think about this?

<img width="477" alt="Screenshot 2020-02-21 at 13 42 07" src="https://user-images.githubusercontent.com/663341/75039169-faaeef80-54af-11ea-9daf-3cc13e27588e.png">

Regards,
Tung

**Comment by deeenes** [comment]
Hi Tung, 

Thanks for your suggestions, I will write a short summary about code formatting style.

Best, 

Denes
