### ISSUE TITLE
Performance profiling

### ISSUE THREAD

**Issue by deeenes** [saezlab/pypath#139]
At some point we should run `cProfile` for all the main database classes and also the `utils.mapping`. Also we should inspect the memory usage. We should take care especially about the methods in `interaction` and `evidence` as these are used extensively for all operations on the network and often run for each components of the network. At moderate size networks these are no issue but for networks above few 100k starts to be slow and also the memory usage is high.

**Comment by npalacioescat** [comment]
Close because not relevant anymore
