### ISSUE TITLE
cannot import name 'main' from 'pypath'

### ISSUE THREAD

**Issue by QUEST2179** [saezlab/pypath#140]
freshly installed using package downloaded from github 
from pypath import main
from pypath import settings
pa = main.PyPath()

        - session ID: `51evl`
        - working directory: `C:\Users\Henry\work\March2020\software\omicMine`
        - logfile: `C:\Users\Henry\work\March2020\software\omicMine\pypath_log\pypath-51evl.log`
        - pypath version: 0.10.6
Traceback (most recent call last):
  File "testPathway.py", line 1, in <module>
    from pypath import main
ImportError: cannot import name 'main' from 'pypath' (C:\Users\Henry\Miniconda3\lib\site-packages\pypath-0.10.6-py3.7.egg\pypath\__init__.py)

**Comment by deeenes** [comment]
Hi,

In the past months we've done a major reorganization of `pypath` and we added a new molecular interaction and network API. We are lagging behind with updating the documentation, apologies about that. Briefly, you are trying to import the legacy molecular interaction module, you can now do this by `from pypath.legacy import main` and then `pa = main.PyPath()`. But maybe it's better to use the new module:

```
from pypath.core import network
from pypath.resources import network as netres

# to load resources in the pathway dataset:
n = network.Network()
n.load(netres.pathway)

# to load OmniPath:
n = network.Network.omnipath()

# to load the transcriptional regulatory network:
n = network.Network.transcription()
```

See some more details in #134, #132, #131, https://saezlab.github.io/pypath/html/reference.html#module-pypath.core.network.

Sorry again for having the pypath guide not updated yet, we are working on it.
If you have any further questions don't hesitate to ask.

Best wishes,

Denes
