### ISSUE TITLE
Can't import curl or data_formats from pypath

### ISSUE THREAD

**Issue by marieBvr** [saezlab/pypath#141]
Hi pypath developers,

I was using pypath six months ago. I have tried to use it again, but my code is failing now.
Here is my code:
```python
import pypath
from pypath import curl
from pypath import data_formats
```
Here is the error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'curl' from 'pypath' (~/anaconda3/envs/pybravo/lib/python3.7/site-packages/pypath/__init__.py)
ImportError: cannot import name 'data_formats' from 'pypath' (~/anaconda3/envs/pybravo/lib/python3.7/site-packages/pypath/__init__.py)
```

Any help would be welcome.
Thanks
Marie.

**Comment by Nic-Nic** [comment]
Dear Marie,
We are currently refactoring the package and many modules have been moved in different folders (almost all of them keep the same name, just changed the directory). You can import data_formats from the resources as:

```python
from pypath.resources import data_formats
```

**Comment by Nic-Nic** [comment]
Similarly for the curl module:
`from pypath.share import curl`

**Comment by marieBvr** [comment]
Thanks @Nic-Nic, it works !

**Comment by marieBvr** [comment]
And what if I used to initialized pyPath with:
`
pa = pypath.PyPath()
`
I couldn't find a file named PyPath in the pypath sources.

**Comment by deeenes** [comment]
Hi Marie,

The `PyPath` class is currently in the `pypath.legacy.main` module:

`
from pypath.legacy.main import PyPath
`

However this class is about to be replaced by `pypath.core.network.Network`, and `data_formats` by `pypath.resources.network`. See more details in #140 

Best,

Denes
