### ISSUE TITLE
Documentation: installation with `pip install pypath`

### ISSUE THREAD

**Issue by numpde** [saezlab/pypath#147]
I think it is worth mentioning in the docs that `pip install pypath` does not install the present package. 

(sorry, this shouldn't be bug-tagged but I don't know how to change this now)

**Comment by Nic-Nic** [comment]
Dear @numpde,

We are aware of this, but it's not any kind of bug, just that in PyPI there is already another package registered with the name `pypath`.
To install with `pip` you have to either point to the git repository or download the binaries and point to the file/directory.
For instance:
`pip install git+https://github.com/saezlab/pypath.git`
`pip install pypath-x.y.z.tar.gz`

Hope this answers your question.

Regards

**Comment by deeenes** [comment]
Hi @numpde, 

Thanks for both of your suggestions, these are indeed helpful to have in the readme, I've just added them.

Best,

Denes
