### ISSUE TITLE
Frequency of database updates?

### ISSUE THREAD

**Issue by humzalikhan** [saezlab/pypath#154]
This is more out of curiosity than it being an actual issue, but how often is the curated OmniPath database updated? I have some code to run protein-associations that outputs different results every few days. Comparing today versus two weeks ago, there is a drastic increase in the number of associations. Of course, this is fine, but just curious about backend updates of this service.

Thanks so much!

**Comment by deeenes** [comment]
Hi,

The contents from the original resources we update only once or twice a year.
However we often do updates which add new resources, improve the processing, fix issues, etc.
Here you find a log of updates: https://archive.omnipathdb.org/README.txt

Best,

Denes

**Comment by deeenes** [comment]
Also I need to note, we are aware our traceability is not perfect. We are working on a system where at any time point the exact download dates and URLs of the original resources can be traced back.

**Comment by humzalikhan** [comment]
Thanks, sounds great!
