### ISSUE TITLE
Best way of access all ligand-receptors

### ISSUE THREAD

**Issue by michalk8** [saezlab/pypath#159]
Hi pypath developers,

I was wondering what would be the best way to access all ligard-receptor pairs from multiple sources?
We're currently getting these pairs just from CellPhone db as:
```python
from pypath.inputs.cellphonedb import cellphonedb_interactions
```
but we'd like to include more.

**Comment by deeenes** [comment]
Hi,

Depending on your preference of language you can use `pypath` or the `OmnipathR` R/Bioconductor package. Also because the latter works from the web service it is much faster and more error proof.

In pypath you need to load a network and build the `intercell` database, then combine them into a data frame annotated with ligand, receptor and potentially other intercellular communication roles:

```
from pypath.core import network
from pypath.resources import network as netres
from pypath import omnipath

# load a network of ligand-receptor resources:
n = network.Network()
n.load(netres.ligand_receptor)
# optionally load further activity flow resources:
n.load(netres.pathway)
# or optionally even more:
n.load(netres.pathway_all)

intercell = omnipath.db.get_db('intercell')

# then combine the intercell annotation with the network:
icn = intercell.network_df(network = n)
# the above will use all composite generic functional classes
# to have only transmitters on the left and receivers on the right side:
icn_tr = i.network_df(network = n, transmitter_receiver = True)
# to have only ligands on the left and receptors on the right side:
icn_lr = i.network_df(
    network = n,
    annot_args_source = {'parent': 'ligand'},
    annot_args_target = {'parent': 'receptor'},
)
# all the above will use only composite generic functional classes
# to do the same for all specific classes:
 icn_lr_spec = i.network_df(
    network = n,
    only_generic = False,
    only_composite = False,
    annot_args_source = {'parent': 'ligand'},
    annot_args_target = {'parent': 'receptor'},
)
# or for certain specific classes, e.g. interleukins and cc chemokines:
icn_lr = i.network_df(
    network = n,
    only_generic = False,
    only_composite = False,
    annot_args_source = {'parent': 'ligand', 'category': {'interleukin', 'chemokine'}},
    annot_args_target = {'parent': 'receptor', 'category': {'interleukin', 'cc_chemokine'}},
)
# to see the category names (e.g. cc_chemokine) here:
i.classes.keys()
# to see the contents of a category:
i.select('cc_chemokine', parent = 'receptor')
```

This database build process depends on network transactions to more than a hundred of original resources, it might take a couple of hours. You can track the progress in the log file. Later you can load the data much quicker, especially if you save the network into pickle.

Alternatively you can use the R package to obtain the same data from the web service:

```
require(OmnipathR)

# all generic composite transmitter-receiver:
icn <- import_intercell_network()
# only ligand-receptor:
icn_lr <- import_intercell_network(
    transmitter_param = list(categories = 'ligand'),
    receiver_param = list(categories = 'receptor')
)
```

I hope this helps, if you have further questions please let me know.

Best,

Denes

**Comment by giovp** [comment]
Hi @deeenes ,

thanks a lot for prompt reply, as @michalk8 mentioned, we would make great use of a python API to access omnipathdb. 
Do you think it would be possible to port the R code to python and thus have a python API that enables same functionality as the R one? We would be happy to contribute to a PR here in pypath if you think it would be useful.

Let us know what you think! thank you!

**Comment by deeenes** [comment]
Good idea, it was already also in my mind, as many people use Python but don't want to do the tedious database building process. I think this should be a separate package, I created a new repo for it: https://github.com/saezlab/omnipath
If you can create pull requests that would be fantastic, we would be super grateful!
Me too I will join the development, but will be able to do so only some weeks later.
The code of the R package can be followed, or for each query type the parameters are listed here, for example for the `interactions` query: https://omnipathdb.org/queries/interactions

**Comment by deeenes** [comment]
This issue had been addressed by @michalk8 creating the `omnipath` module: https://github.com/saezlab/omnipath
