### ISSUE TITLE
Wrong download url for HPA

### ISSUE THREAD

**Issue by willov** [saezlab/pypath#16]
dataio seems to want to  download HPA information from https://www.proteinatlas.org/download/normal_tissue.csv.zip , but that link does not exist anymore.
https://www.proteinatlas.org/download/normal_tissue.tsv.zip is the new one. 
(changed from csv to tsv)
I assume that they changed from comma to tab as delim, I guess this will also cause further problems?

**Comment by deeenes** [comment]
Hi Willov, Yes there was a format change at HPA and also they changed the layout of the cancer data. I updated the methods so now it should work (from 0.7.61).

**Comment by willov** [comment]
Works for me now!
