### ISSUE TITLE
PyPath object has no attribute error

### ISSUE THREAD

**Issue by vthawfeek** [saezlab/pypath#163]
Hi,
I'm new to PyPath and may be am missing something very basic here. I'm trying to use the set_transcription_factors() method in PyPath object and get the following error: 

> 'PyPath' object has no attribute 'tfs_list'.

**My code:**
    from pypath.legacy import main
    pa = main.PyPath()
    pa.init_network()
    pa.set_transcription_factors()

**My environment:**
Python version 3.8.3
Anaconda Jupiter notebook
macOS Catalina (Version 10.15.7)

Please help me with this. 

Many thanks!
Thawfeek

**Comment by vthawfeek** [comment]
Further, the online documentation seems to be outdated. For instance, **from pypath import main** does not work and I need to use **from pypath.legacy import main** instead. Is there an updated documentation guide somewhere that I can use for these changes?

**Comment by deeenes** [comment]
Hi,

This part of the documentation is indeed outdated and will be updated in the near future. Apologies for the inconvenience.

First of all, I recommend to read this: https://github.com/saezlab/omnipath, just to see if maybe the R or Python web service client is more suitable for your purpose.
`pypath` has a new network API, you can load a network like this:

```
from pypath.core import network
from pypath.resources import network as netres
n = network.Network()
n.load(netres.pathway) # this loads the literature curated PPI
# or to load "OmniPath" with all the extra datasets:
o = network.Network.omnipath()
# or you can build it as a database and then later load it faster:
from pypath import omnipath
o = omnipath.db.get_db('omnipath')
```

The proteins in the network are in the `nodes` attribute:
```
n.nodes
# ...
# 'Q9BYB0': <Entity: SHANK3>,
# 'Q9BYE0': <Entity: HES7>,
# 'Q9BYE7': <Entity: PCGF6>,
# 'Q9BYE9': <Entity: CDHR2>,
# 'Q9BYF1': <Entity: ACE2>,
# 'Q9BYG3': <Entity: NIFK>,
# 'Q9BYG4': <Entity: PARD6G>,
# ...
```

Alternatively, the network can be accessed as a `pandas.DataFrame`:

```
n.make_df()
n.df
```

The annotations about protein functions, such as transcription factor, are now available by the `annot` module:

```
from pypath.core import annot
tfs = annot.Tfcensus()
```

To get the TFs in the network:

```
tfs_in_network = set(tfs.proteins) & n.get_protein_identifiers()
```

I hope this helps.

Best,

Denes

**Comment by vthawfeek** [comment]
Thanks for the information, Denes! This is very useful. However, I'm having issues with the annot module in your code.

`from pypath.core import annot`
`tfs = annot.Tfcensus()`

When I run this, I get the following TypeErrror in /pypath/inputs/main.py at line 4497:

> descriptor 'union' of 'set' object needs an argument

Could you please advise.

Many thanks,
Thawfeek

**Comment by deeenes** [comment]
True, the journal changed the URL, I updated it in 753337e3

**Comment by vthawfeek** [comment]
Thanks Denes! It works now.
