### ISSUE TITLE
500 Error Again

### ISSUE THREAD

**Issue by pyanne2000** [saezlab/pypath#169]
Hi, It's 500 error again, please check it.
![截屏2021-03-14 下午8 20 54](https://user-images.githubusercontent.com/34863828/111068208-c9fa8780-8502-11eb-8680-e96c7aef17ba.png)

**Comment by deeenes** [comment]
Hi,

Thanks for reporting this. The reason was a missing iptables rule, now it's working again.

Best,

Denes
