### ISSUE TITLE
DisGenNet change of download URL/format

### ISSUE THREAD

**Issue by willov** [saezlab/pypath#17]
It seems as though DisGenNet also has changed url/format. 
Old:  'http://www.disgenet.org/ds/DisGeNET/results/curated_gene_disease_associations.tar.gz'
New: 'http://www.disgenet.org/ds/DisGeNET/results/curated_gene_disease_associations.tsv.gz'

**Comment by deeenes** [comment]
Thanks willov, I fixed this in 0.7.63. Also added options to load DisGeNet using UMLS IDs instead of disease names or load additional annotations from the database.
