### ISSUE TITLE
Update attribute name in installation script

### ISSUE THREAD

**Issue by ticarki** [saezlab/pypath#172]
**Describe the bug**
The Mac installation scripts seem to be outdated. They fail to test the successful installation of bypath due to an update of an attribute name. `pypath.PyPath()` now id `bypath.pypath()`

**To Reproduce**
`./src/scripts/mac-install-brew.sh `
or
`./src/scripts/mac-install-conda.sh `

**Expected behavior**
Successful installation and test

**Traceback**
The both bash scripts must be updated in line 300 and 162 respectively:

``` sh
$CONDAPY -c "import pypath; pa = pypath.PyPath()" >/dev/null 2>&1
```
is now
```sh
$CONDAPY -c "import pypath; pa = pypath.pypath()" >/dev/null 2>&1
```

**Desktop:**
 - OS: [iOS 11.2.3 - ARM]
 - Python version: [3.9]
 - Version or commit hash [dbe7db6]

**Comment by deeenes** [comment]
Hi, Thanks for noticing this. I fixed it, however these scripts are kind of deprecated and I am thinking about removing them. Also on Mac a simple pip install should work: `pip install pypath-omnipath`.
