### ISSUE TITLE
Logging: PyPath overwrites severity level of root logger

### ISSUE THREAD

**Issue by CPerscheid** [saezlab/pypath#175]
In log.py, mapping.py, uniprot.py, reflists.py, taxonomy.py, and homology.py you overwrite the severity level of the root logger:
`timeloop.app.logging.disable(level=9999)`

When I import pypath and implement my own logging functionality via the logging module, none of the messages are handled because the severity level was set so high by the above statements.

A workaround for this issue is to reset the severity level
`logging.disable(0)`
after importing pypath modules.

Please fix that. :)

**Comment by deeenes** [comment]
Hi Cindy,

I am sorry about that. Now I set the log level on the `Timeloop` instances:
```
tl = timeloop.Timeloop()
tl.logger.setLevel(99)
```
I think this won't affect the root logger.

Best,

Denes
