### ISSUE TITLE
li2012 data seems to have moved

### ISSUE THREAD

**Issue by willov** [saezlab/pypath#18]
I'm getting 0 byte sized file downloaded. 
Going to the url in a browser yields the desired result. 
Running (in terminal) curl -O -L -k   'http://genome.cshlp.org/content/suppl/2011/12/27/gr.128819.111.DC1/Supplementary_files_S1-S5.xls'
also yields the desired file. 

I assume they have moved to https or something similar. 

DataIO row 4256

**Comment by deeenes** [comment]
Hi Willov,

I tested and works fine for me. It might happened that there was a problem at your first download and an empty file remained in your cache directory. If you remove that file or load the data under `pypath.curl.cache_off()` context it will download the file again and probably will work fine.

```
import pypath.dataio

with pypath.curl.cache_off():
    li = list(pypath.dataio.get_li2012())

li[0]
## ['BCR', 'BCR/177', 'ABL', 'PTPN SH2', 'CTK_Cytoplasm', 'ubiquitous', 'PPP']
```
