### ISSUE TITLE
Peer certificate cannot be authenticated with given CA certificates

### ISSUE THREAD

**Issue by HuairenZhang** [saezlab/pypath#184]
I was trying to load the OmniPath Interactions with R, but there is error. the error message says that cannot open the connection to omnipathdb.org and the url status is Peer certificate cannot be authenticated with given CA certificates. Could you please help? Thank you.

**Comment by deeenes** [comment]
Hello,

I hope you already found the solution. If you haven't, the reason is that your OS doesn't have the [ISRG Root X1](https://letsencrypt.org/certificates/) certificate installed, which means that your certificate store is very old. The solution is to update it.

Best,

Denes
