### ISSUE TITLE
CellphoneDB v4

### ISSUE THREAD

**Issue by JanLeipzig** [saezlab/pypath#200]
Hi,

CellphoneDB recently released version v4 of its database and I was wondering if it will be included into the consensus resource of LIANA anytime soon.
I'm very interested in the "non-peptidic molecules (i.e., not encoded by a gene) acting as ligands. Examples of these include steroid hormones (e.g., estrogen)." As far as I could tell there are no steroid hormones included in the consensus resource at the moment. It would be very convenient if they would become part of the LIANA consensus so one could use it without manual additions.

In the documentation it is mentioned that you "plan to continuously update this resource". Do you have a general plan how to include updates of the different databases once they become available?
(If you plan to update the consensus occasionally some kind of version number to keep track of that, would be nice.)

Thank you very much

**Comment by dbdimitrov** [comment]
ping @deeenes  :) related to the email from Julio

**Comment by deeenes** [comment]
Hi, I don't know why I haven't answered this one, I'm very sorry about that! CellPhoneDB is up to date in OmniPath. The tables that [OmniPath uses](https://github.com/saezlab/pypath/blob/cbedc99376c0be55f0c154d81f231a8c6de14d8b/pypath/resources/urls.py#L1116) have been [last updated 8 March 2023](https://github.com/ventolab/cellphonedb-data/tree/master/data) (4.1.0), while 5 April 2023 there was [a full contents update](https://archive.omnipathdb.org/README.txt).

I know it's not too straightforward to find this information. We're preparing a better solution with clear versioning and database build reports, stay tuned for that :)

**Comment by saeedfc** [comment]
Hi,
Thanks for the amazing resource and tool!
CellPhoneDB just have a new update (v5). I guess it is not yet updated in if I fetch now using OmniPathR? And maybe you want to consider allowing different version by appending ..v4, ..v5 etc.

Kind regards,
Saeed
