### ISSUE TITLE
Unable to create a network

### ISSUE THREAD

**Issue by bimwu** [saezlab/pypath#22]
Hello, 

I am new to OmniPath. After installation, I tried to extract a network using the sample code provided on OmniPath website.

import pypath
pa = pypath.PyPath()
pa.load_resources({'signor': pypath.data_formats.pathway['signor']})

However, I was unable to obtain any interaction or node. 

![image](https://user-images.githubusercontent.com/40481051/43689919-4f2fc910-98cf-11e8-82ac-b8f34e0856c3.png)

I wonder if I can get some suggestions for trouble shooting? Thank you

**Comment by deeenes** [comment]
Dear Bimwu,

I think you have the same issue as here: https://github.com/saezlab/pypath/issues/21

Please tell me if the solution presented there (update pypath and purge cache) makes it work for you.

Best,

Denes
