### ISSUE TITLE
Faulty behavior in function generation in kegg_api module

### ISSUE THREAD

**Issue by MelihDarcanxyz** [saezlab/pypath#220]
**Describe the bug**
[This function](https://github.com/saezlab/pypath/blob/3820c3a28c13ce701f1d2b5f9ac6e00834c757da/pypath/inputs/kegg_api.py#L51) in the kegg_api module has a faulty behavior.

It iterates through the types of relations but the last relation it takes to generate function overwrites all of the functions that generated before. So according to this function, pathway_gene relation is the last generated function. It turns out all of the functions generated before, even though their name is drug_pathway or etc., are the clones of the last generated function.

Any ideas on how to fix this? Also I will open a PR to fix some bugs in kegg_api, I suggest you to merge it in local before trying, otherwise it will not work.

**Comment by MelihDarcanxyz** [comment]
https://github.com/saezlab/pypath/pull/221

**Comment by ervau** [comment]
@deeenes  could you please take a quick look at this issue when you have a moment? It appears to be a bug in the kegg_api module's function that is causing issues with overwriting previously generated functions, and is becoming a blocker for our project. Thank you!
