### ISSUE TITLE
Missing required dependancy psutils

### ISSUE THREAD

**Issue by PauBadiaM** [saezlab/pypath#233]
I noticed that `decoupler` builds where failing due to `pypath` missing the `psutils` dependancy

To reproduce install `pypath-omnipath` from pip and then run this:
```
from pypath.utils import homology
```

Here's the log of the error: https://github.com/saezlab/decoupler-py/actions/runs/4670447977/jobs/8290597448#step:6:557

A solution to this problem would be to add `psutils` as a required dependency during installation.

**Comment by slobentanzer** [comment]
+1, have the same issue with biocypher

**Comment by deeenes** [comment]
Has been fixed in 1e279d -- I guess you install from PyPI, I'll soon push a build there :)
