### ISSUE TITLE
Cache management: Setting a different cache directory

### ISSUE THREAD

**Issue by t-silvers** [saezlab/pypath#238]
**Describe the bug**
[It's unclear](https://pypath.omnipathdb.org/notebooks/manual.html#Cache-management-and-customization) how to set a caching directory to overwrite the default (`~/.pypath/pickles/`)

**Expected behavior**
```python
from pypath.share import CacheManager
from pypath import omnipath

cache_manager = CacheManager()
cache_manager.set_cache_dir('/path/to/cachedir/')

co = omnipath.db.get_db('complex')
print(co.pickle_file)
# '/path/to/cachedir/complexes.pickle'
```

**Comment by deeenes** [comment]
Hello Thomas,

Pypath has cache directory for the downloaded raw and some preprocessed contents (`cachedir`) and another one for saving built databases as pickles (`pickle_dir`). These can be controlled by the `settings` module:

```
from pypath.share import settings

# the current values:
settings.get('cachedir')
# '/home/denes/.pypath/cache'
settings.get('pickle_dir')
# '/home/denes/.pypath/pickles'

# setting new values:
settings.setup(cachedir = './pypath_cache', pickle_dir = './pypath_pickles')
```

I hope this helps, later I'll make it more clear in the docs. And a complete overhaul of the caching functionality is due very soon, after that it will be more convenient to use.

Best,

Denes

**Comment by t-silvers** [comment]
Awesome, thanks for the quick reply 🍻 !

Excited to see what's coming down the pike. I have a couple other cache management wish-list items. These items may already be discussed elsewhere (or may even already be well-handled now).

- concurrent read/writes in a multi-user environment
- shared caching between python and R users (of `OmnipathR`)

Happy to re-post elsewhere if useful for your roadmap, otherwise I'll close

**Comment by deeenes** [comment]
Thanks, these are useful feedback, the first one will likely be realised, the second one not sure, I have to think about that.
