### ISSUE TITLE
AttributeError: 'module' object has no attribute 'POSTREDIR' when trying to load_all_pathways (py2.7)

### ISSUE THREAD

**Issue by IvoLeist** [saezlab/pypath#26]
Dear Denes,

thank you for processing and solving the issues so quickly the last time :)
The BufferedIO error somehow magically disappeared as well :D

Unfortunately I run today in one other error trying to load_all_pathways:
Downloading data from Signor: initializing:   0%|          | 0.00/62.0 [00:00<?, ?it/s]
runs in the following error:
> 
> ----> 6 pa.load_all_pathways() #load all resources 
> 
> /home/usr/.local/lib/python2.7/site-packages/pypath/main.pyc in load_all_pathways(self, graph)
>    7406     def load_all_pathways(self, graph=None):
>    7407         self.kegg_pathways(graph=graph)
> -> 7408         self.signor_pathways(graph=graph)
>    7409         self.pathway_attributes(graph=graph)
>    7410 
> 
> /home/usr/.local/lib/python2.7/site-packages/pypath/main.pyc in signor_pathways(self, graph)
>    7457 
>    7458     def signor_pathways(self, graph=None):
> -> 7459         self.load_pathways('signor', graph=graph)
>    7460 
>    7461     def kegg_pathways(self, graph=None):
> 
> /home/usr/.local/lib/python2.7/site-packages/pypath/main.pyc in load_pathways(self, source, graph)
>    7431         g = self.graph if graph is None else graph
>    7432         nodDct = dict(zip(g.vs['name'], xrange(g.vcount())))
> -> 7433         proteins_pws, interactions_pws = self.get_pathways(source)
>    7434         g.vs[attrname] = [set([]) for _ in g.vs]
>    7435         g.es[attrname] = [set([]) for _ in g.es]
> 
> /home/usr/.local/lib/python2.7/site-packages/pypath/main.pyc in get_pathways(self, source)
>    7373         if hasattr(dataio, attrname):
>    7374             fun = getattr(dataio, attrname)
> -> 7375             proteins_pws, interactions_pws = fun(mapper=self.mapper)
>    7376         return proteins_pws, interactions_pws
>    7377 
> 
> /home/usr/.local/lib/python2.7/site-packages/pypath/dataio.pyc in signor_pathways(**kwargs)
>    5145             silent = True,
>    5146             large = True,
> -> 5147             binary_data = binary_data
>    5148         )
>    5149 
> 
> /home/usr/.local/lib/python2.7/site-packages/pypath/curl.pyc in __init__(self, url, silent, get, post, req_headers, cache, debug, outf, compr, encoding, files_needed, timeout, init_url, init_fun, init_use_cache, follow, large, override_post, init_headers, return_headers, compressed, binary_data, write_cache, force_quote, sftp_user, sftp_passwd, sftp_passwd_file, sftp_port, sftp_host, sftp_ask, setup, call, process, retries, cache_dir)
>     758                 self.progress_setup()
>     759                 if setup:
> --> 760                     self.curl_setup()
>     761                 if call:
>     762                     self.curl_call()
> 
> /home/usr/.local/lib/python2.7/site-packages/pypath/curl.pyc in curl_setup(self, url)
>     947         self.set_debug()
>     948         self.set_post()
> --> 949         self.set_binary_data()
>     950         self.set_req_headers()
>     951         self.set_resp_headers()
> 
> /home/usr/.local/lib/python2.7/site-packages/pypath/curl.pyc in set_binary_data(self)
>     903             self.curl.setopt(pycurl.READFUNCTION, self.binary_data_file.read)
>     904             self.curl.setopt(pycurl.CUSTOMREQUEST, 'POST')
> --> 905             self.curl.setopt(pycurl.POSTREDIR, 3)
>     906 
>     907     def curl_init(self, url=False):
> 
> AttributeError: 'module' object has no attribute 'POSTREDIR'

Best,
Ivo

**Comment by deeenes** [comment]
Hi Ivo,

This looks strange as `pycurl` module really has `POSTREDIR` attribute.
Where your module comes from? E.g. create an empty directory, start `python2` and do:

```
>>> import pycurl
>>> pycurl
<module 'pycurl' from '/usr/lib/python2.7/site-packages/pycurl.so'>
>>> pycurl.POSTREDIR
161
```

Does it look different at you?

Best,

Denes

**Comment by IvoLeist** [comment]
Hi Denes,

was just about to update this issue (anyway thanks for the fast reply) updating my pycurl to the latest version indeed resolved that issue however a new error has arised but you can close that issue and I"ll open  an new one ;D

Best,
Ivo
