### ISSUE TITLE
Database (partially?) down

### ISSUE THREAD

**Issue by pokedthefrog** [saezlab/pypath#262]
At the moment, trying to access [https://omnipathdb.org/info](https://omnipathdb.org/info), the [DoRothEA interaction dataset](https://omnipathdb.org/interactions/?datasets=dorothea), or querying for [transcriptional interactions in general](https://omnipathdb.org/interactions/?types=transcriptional), all result in `500 Internal Server Error`. Other datasets or interaction types don't seem affected by the issue.

Thanks a lot for the help! 😊

**Comment by deeenes** [comment]
Hi @pokedthefrog,

Thanks for reporting this, it revealed two minor issues in the server that I've just fixed now. Please let me know if it still doesn't work.
