### ISSUE TITLE
AttributeError: 'generator' object has no attribute 'read' in load_all_pathways (py2.7)

### ISSUE THREAD

**Issue by IvoLeist** [saezlab/pypath#27]
Hi Denes,

here as promised the new issue ;D So far I have not reinitialised the network but restarted load_all_pathways in the same jupyter notebook I will let you know if that resolves that issue.

in the meanwhile that is my traceback:

> AttributeError                            Traceback (most recent call last)
> <ipython-input-45-d51050efd0d0> in <module>()
> ----> 1 pa.load_all_pathways()
> 
> /home/usr/.local/lib/python2.7/site-packages/pypath/main.pyc in load_all_pathways(self, graph)
>    7406     def load_all_pathways(self, graph=None):
>    7407         self.kegg_pathways(graph=graph)
> -> 7408         self.signor_pathways(graph=graph)
>    7409         self.pathway_attributes(graph=graph)
>    7410 
> 
> /home/usr/.local/lib/python2.7/site-packages/pypath/main.pyc in signor_pathways(self, graph)
>    7457 
>    7458     def signor_pathways(self, graph=None):
> -> 7459         self.load_pathways('signor', graph=graph)
>    7460 
>    7461     def kegg_pathways(self, graph=None):
> 
> /home/usr/.local/lib/python2.7/site-packages/pypath/main.pyc in load_pathways(self, source, graph)
>    7431         g = self.graph if graph is None else graph
>    7432         nodDct = dict(zip(g.vs['name'], xrange(g.vcount())))
> -> 7433         proteins_pws, interactions_pws = self.get_pathways(source)
>    7434         g.vs[attrname] = [set([]) for _ in g.vs]
>    7435         g.es[attrname] = [set([]) for _ in g.es]
> 
> /home/usr/.local/lib/python2.7/site-packages/pypath/main.pyc in get_pathways(self, source)
>    7373         if hasattr(dataio, attrname):
>    7374             fun = getattr(dataio, attrname)
> -> 7375             proteins_pws, interactions_pws = fun(mapper=self.mapper)
>    7376         return proteins_pws, interactions_pws
>    7377 
> 
> /home/usr/.local/lib/python2.7/site-packages/pypath/dataio.pyc in signor_pathways(**kwargs)
>    5150         sep = '@#@#@'
>    5151         lines = csv_sep_change(
> -> 5152             c_pw.result.read().decode('utf-8'),
>    5153             '\t',
>    5154             sep
> 
> AttributeError: 'generator' object has no attribute 'read

Best,
Ivo

**Comment by deeenes** [comment]
Hi Ivo,

Fixed in https://github.com/saezlab/pypath/commit/a7810f594f82da75fce11e95e29d683564ffc38d
Thanks for testing and reporting! ;)

Best,

Denes
