### ISSUE TITLE
ICELLNET Update

### ISSUE THREAD

**Issue by dbdimitrov** [saezlab/pypath#271]
ICELLNET was recently updated.

I noticed that the url in resources is out of date:
https://raw.githubusercontent.com/soumelis-lab/ICELLNET/master/data/ICELLNETdb.csv

**Comment by Nic-Nic** [comment]
Hi Daniel,

Where did you see the out of date URL? I have checked in resources ([here](https://github.com/saezlab/pypath/blame/bbee7b99d9bd4ff736eb4ecb2ece8b07bb18a3fb/pypath/resources/urls.py#L1325)) and it's the same URL you posted :thinking:

**Comment by dbdimitrov** [comment]
I don't remember :smile:, seems like they updated the url very recently so it should be good.

I will close the issue.

Thanks!
