### ISSUE TITLE
TypeError: a class that defines __slots__ without defining __getstate__ cannot be pickled in save_network (py2.7)

### ISSUE THREAD

**Issue by IvoLeist** [saezlab/pypath#28]
Dear Denes,

thank you for fixing the last bug again so quickly! :) 

Here is another one ;D This error arises when calling pa.save_network()

> TypeError                                 Traceback (most recent call last)
> <ipython-input-6-76d313c226e2> in <module>()
> ----> 1 pa.save_network()
> 
> /home/user/.local/lib/python2.7/site-packages/pypath/main.pyc in save_network(self, pfile)
>     837         pfile = pfile if pfile is not None \
>     838             else os.path.join('cache', 'default_network.pickle')
> --> 839         pickle.dump(self.graph, open(pfile, 'wb'))
>     840     ###
>     841     # functions to read networks from text files or mysql
> 
> /usr/lib64/python2.7/copy_reg.pyc in _reduce_ex(self, proto)
>      75     except AttributeError:
>      76         if getattr(self, "__slots__", None):
> ---> 77             raise TypeError("a class that defines __slots__ without "
>      78                             "defining __getstate__ cannot be pickled")
>      79         try:
> 
> TypeError: a class that defines __slots__ without defining __getstate__ cannot be pickled

Best,
Ivo

**Comment by deeenes** [comment]
Hi Ivo,

Should be fixed here: https://github.com/saezlab/pypath/commit/ade7f7613d8b610519f5213cb9e047c6b9d77e83

Best,

Denes
