### ISSUE TITLE
pa.get_edge allways retuns NONE

### ISSUE THREAD

**Issue by IvoLeist** [saezlab/pypath#30]
Dear  Denes,

now all the loading and creating of the graph is working for me :)
However now I am stuck with querying some things from your graph
Following your jupyter notebook: http://pypath.omnipathdb.org/notebooks/pypath_build_networks.html

In Step 6: Further attributes in the PyPath object
Accessing the edges per gene name or uniprot is not possible:

get_edge allways retuns NONE
`pa.get_edge(pa.up('P42858'), pa.up('Q02447'))` --> NONE
`pa.get_edge(pa.gs('HTT'), pa.gs('SP3'))` --> NONE

although this edge should exits, because:
`pa.graph.es[0]["dirs"]`

prints out:

> Directions and signs of interaction between P42858 and Q02447
> 	P42858 ==== Q02447 :: IntAct
> 

Or did I missunderstood something in your tutorial ?

Best,
Ivo

**Comment by deeenes** [comment]
Hi Ivo,

Apologies for late reply!

You don't need here `up`, you can just pass directly UniProt IDs.
It was wrong in the tutorial. I fixed the tutorial and also `get_edge` to accept `igraph.Vertex` objects.

Best,

Denes
