### ISSUE TITLE
pa.get_edge still buggy (in py2.7)

### ISSUE THREAD

**Issue by IvoLeist** [saezlab/pypath#33]
Dear Denes,

I am sorry to bother you again but somehow  the get_edge function is still buggy (in py2.7)

When I try to reproduce the change in your update of the jupyter notebook
it runs in the following error (does not matter if gene name or uniprot id)

> TypeError                                 Traceback (most recent call last)
> <ipython-input-46-b1e2e9904893> in <module>()
> ----> 1 edge = pa.graph.es[pa.get_edge('EGF','EGFR')]
> 
> TypeError: igraph supports string attribute names only, got <type 'igraph.Edge'>

Further on the function still does not seem to support vertex objects:
```
gene1_vertexObj = list(signaling_graph.gs_stimulated_by("RHOA").vs())[0]
gene2_vertexObj = list(signaling_graph.gs_stimulated_by("RHOA").vs())[1]
```

> TypeError                                 Traceback (most recent call last)
> <ipython-input-50-a0253fdf1260> in <module>()
> ----> 1 edge = pa.graph.es[pa.get_edge(gene1_vertexObj,gene2_vertexObj)]
> 
> TypeError: igraph supports string attribute names only, got <type 'NoneType'>

I Already double checked if I have the newest version of pypath:
> > New session started,
> 	session ID: 'k84ar'
> 	logfile: './log/k84ar.log'
> 	pypath version: 0.7.98
> 	:: Network loaded from `cache/signaling_network.pickle`. 14596 nodes, 118739 edges.      
> 	:: Loading 'genesymbol' to 'uniprot' mapping table

Best,
Ivo

**Comment by deeenes** [comment]
Hi Ivo,

> Dear Denes,
> 
> I am sorry to bother you again but somehow the get_edge function is still buggy (in py2.7)
> 
> When I try to reproduce the change in your update of the jupyter notebook
> it runs in the following error (does not matter if gene name or uniprot id)
> 
> > TypeError                                 Traceback (most recent call last)
> >  in ()
> > ----> 1 edge = pa.graph.es[pa.get_edge('EGF','EGFR')]
> > TypeError: igraph supports string attribute names only, got <type 'igraph.Edge'>

`get_edge` returns and `igraph.Edge` object, not edge index. You can access the index by the `index` attribute:

```
>>> e = pa.get_edge('EGF', 'EGFR')
>>> type(e)
<class 'igraph.Edge'>
>>> e.index
2209
>>> pa.graph.es[2209] == e
True
```

> 
> Further on the function still does not seem to support vertex objects:
> 
> ```
> gene1_vertexObj = list(signaling_graph.gs_stimulated_by("RHOA").vs())[0]
> gene2_vertexObj = list(signaling_graph.gs_stimulated_by("RHOA").vs())[1]
> ```
> 
> > TypeError                                 Traceback (most recent call last)
> >  in ()
> > ----> 1 edge = pa.graph.es[pa.get_edge(gene1_vertexObj,gene2_vertexObj)]
> > TypeError: igraph supports string attribute names only, got <type 'NoneType'>

`get_edge` returns `None` if no edge exists between the 2 nodes. Both vertices you queried are stimulates `RHOA` (note, names of these methods are confusing for many, `stimulated_by('RHOA')` returns the nodes which stimulate `RHOA` not those stimulated by `RHOA`) hence these 2 vertices definitely have connections to `RHOA` but we don't know if they are connected to each other. 

```
>>> v0 = list(pa.gs_stimulated_by("RHOA").vs())[0]
>>> v1 = list(pa.gs_stimulated_by("RHOA").vs())[1]
>>> type( pa.get_edge(v0, v1))
<class 'NoneType'>
>>> type(pa.get_edge('RHOA', v0, directed = True))
<class 'igraph.Edge'>
>>> type(pa.get_edge('RHOA', v1, directed = True))
<class 'igraph.Edge'>
```

How you got this error is simple: `pa.graph.es[None]` always gives this error.

Best,

Denes

> 
> I Already double checked if I have the newest version of pypath:
> 
> > > New session started,
> > > session ID: 'k84ar'
> > > logfile: './log/k84ar.log'
> > > pypath version: 0.7.98
> > > :: Network loaded from `cache/signaling_network.pickle`. 14596 nodes, 118739 edges.
> > > :: Loading 'genesymbol' to 'uniprot' mapping table
> 
> Best,
> Ivo

**Comment by IvoLeist** [comment]
Dear Denes,

thanks again a lot for the in-depth explanation of my issue :)
I hope I now fully understood your tool and I am looking forward of 
discussing (tomorrow) with you how to implement it in my web app ;)

However going through your tutorials back and forth I might have found 
another bug (?) (see next issue) but no worries don't spend to much time on it
since I do not really need that feature for my web app just thought it is worth mentioning ;-)

Best,
Ivo
