### ISSUE TITLE
neighborhood methods: TypeError: argument 2 to map() must support iteration (in py2.7)

### ISSUE THREAD

**Issue by IvoLeist** [saezlab/pypath#34]
Hello again :D,

going back and forth through your tutorial
http://pypath.omnipathdb.org/notebooks/pypath_build_networks.html 
I found in "In [40]" another issue:
print list(pa.gs_neighborhood("EGFR").gs())
runs into the following error:

> ---------------------------------------------------------------------------
> TypeError                                 Traceback (most recent call last)
> <ipython-input-240-f20c531d2268> in <module>()
>       1 #The direct neighbors, without being aware of the directions are retrieved by neighbors methods:
> ----> 2 print list(pa.gs_neighborhood("EGFR").gs())
> 

> /home/user/.local/lib/python2.7/site-packages/pypath/main.pyc in gs_neighborhood(self, genesymbols, order, mode)
>    4994             genesymbols = [genesymbols]
>    4995         vs = self.genesymbols(genesymbols)
> -> 4996         return self._neighborhood(vs, order=order, mode=mode)
>    4997 
>    4998     def neighborhood(self, identifiers, order=1, mode='ALL'):
> 
> /home/user/.local/lib/python2.7/site-packages/pypath/main.pyc in _neighborhood(self, vs, order, mode)
>    4980                     lambda a, b: a.extend(b),
>    4981                     self.graph.neighborhood(
> -> 4982                         vs, order=order, mode=mode), [])),
>    4983             self.nodNam,
>    4984             self.nodLab)
> 
> TypeError: argument 2 to map() must support iteration
> 

*Note since I do not really need that feature for my web app
treat this issue with a low priority

Best,
Ivo

**Comment by deeenes** [comment]
Thanks, fixed in https://github.com/saezlab/pypath/commit/92da71fbdb34e8ccae4d006ad6a77c107afdb6d9
