### ISSUE TITLE
Add alternative initialization methods

### ISSUE THREAD

**Issue by deeenes** [saezlab/pypath#35]
E.g. instead of 
```
pa = pypath.PyPath()
pa.load_ligand_receptor_network()
```

like this:

```
pa = pypath.PyPath.init_ligand_receptor_network()
```

**Comment by Nic-Nic** [comment]
I'm kind of getting into Python decorators lately and I think a possible way to do this is to add the `@staticmethod` one before the network loader methods. Even though, not sure 100% if this approach would do as intended or just assign the return of such method to `pa`... Still worth a try

**Comment by deeenes** [comment]
I have done it this way: https://github.com/saezlab/lipyd/blob/c4645489e50a9b93b0fd6aa9b7f5f68e0c657d91/src/lipyd/ms2.py#L398
Maybe I copied the method from igraph: https://github.com/igraph/python-igraph/blob/b570c4c9053cc9f7f7edf58b056fc74739826092/igraph/__init__.py#L2624
But indeed `@staticmethod` could work if you use the class name

**Comment by deeenes** [comment]
Done for `pypath.core.network.Network`
