### ISSUE TITLE
New reader module

### ISSUE THREAD

**Issue by deeenes** [saezlab/pypath#36]
-- The pre-processing of network data should be organized in a separate module.
-- Here we should have classes which are responsible for processing an entire dataset, one line and one field in the line.
-- Just like until now, we should provide users to provide simple instructions for processing in simple cases and give highest flexibility in complicated cases.
-- We should keep in mind that one line might provide 0, 1 or more interactions for the network and one input source might provide different types of interactions and sometimes we might need only some of them, e.g. from Signor we can load only protein-protein but also small_molecule-protein, now we do it by reading the file twice.

**Comment by deeenes** [comment]
This has been started by @Donkey1818  and is in progress.

**Comment by Nic-Nic** [comment]
Hasn't this been addressed in previous rounds of refactoring? If not, we can reopen issue. Closing otherwise
