### ISSUE TITLE
New URL for matrixdb

### ISSUE THREAD

**Issue by ManavalanG** [saezlab/pypath#4]
MatrixDB has new url- http://matrixdb.univ-lyon1.fr/download/matrixdb_CORE.tab.gz.
Currently used one (http://matrixdb.ibcp.fr/download/matrixdb_CORE.tab.gz) is broken.

On unrelated note, why aren't downloaded cache files named using human-readabale filenames?

**Comment by deeenes** [comment]
Thanks @ManavalanG , good to know! Also they have ~100 more interactions. I updated this in 0.6.41.
