### ISSUE TITLE
User level cache directory by default

### ISSUE THREAD

**Issue by deeenes** [saezlab/pypath#40]
Currently by default `pypath` creates and uses a directory named `cache` in the current working directory. This is not the best practice:
-- Default cache should be in `/home/user/.pypath/cache`
-- Outside of this the directory should be called by default `pypath-cache`
(of course users always can give custom path for cache)

**Comment by Nic-Nic** [comment]
We should be careful about this since not everybody may have the cache directory in the same path (eg. different OS). Maybe the `os` module offers some option for this?

**Comment by deeenes** [comment]
`os.path.expanduser()`?

**Comment by Nic-Nic** [comment]
That could work

**Comment by deeenes** [comment]
Done
