### ISSUE TITLE
Problems with PyPath.export_ptms_tab()

### ISSUE THREAD

**Issue by Nic-Nic** [saezlab/pypath#64]
There seems to be a problem when adding the references to the tab file rows, as it raises `TypeError: sequence item 0: expected string, Reference found`.
Also, as soon as the prompt comes back, another exception is raised (something internal to Python threads and sets) [!?]:
```
Exception in thread Thread-295:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/user/.local/lib/python2.7/site-packages/tqdm/_tqdm.py", line 144, in run
    for instance in self.tqdm_cls._instances:
  File "/usr/lib/python2.7/_weakrefset.py", line 60, in __iter__
    for itemref in self.data:
RuntimeError: Set changed size during iteration
```
Is this only me or?

**Comment by deeenes** [comment]
We should replace it with `PtmAggregator.make_df()` as it is in websrvtab.WebserviceTables.pmts()`

**Comment by Nic-Nic** [comment]
I guess you meant `ptms()` :laughing: 
Also, `PyPath.export_struct_tab()` raises the same `TypeError`
If these methods are properly implemented in `websrvtab.py`, should we remove the ones from the `PyPath` class or redirect its export functions to calls on `WebserviceTables`?

**Comment by deeenes** [comment]
Ideally we should add to `pypath.export` a small class accepting or creating a `pypath.ptm.PtmAggregator` object, calling `make_df` and then `to_csv(sep = '\t')`...

**Comment by Nic-Nic** [comment]
This should be fixed with recent upgrades
