### ISSUE TITLE
Problem with Cytoscape Plugin

### ISSUE THREAD

**Issue by ucsdwxu** [saezlab/pypath#67]
Hi,
I installed the Cytoscape plugin for Omnipath but when I tried to confirm selections on the database search, it always came out error message saying that permission denied. Would please help advise?

Thank you.

**Comment by ucsdwxu** [comment]
> Hi, I am sorry to hear this. I can confirm the issue is not with the web service. We might need to contact the developer of the Cytoscape plugin, I would like to ask a little patience. We will return to you soon. Best, Denes El mié., 19 dic. 2018 a las 23:09, ucsdwxu (<notifications@github.com>) escribió:
> […](#)
> Hi, I installed the Cytoscape plugin for Omnipath but when I tried to confirm selections on the database search, it always came out error message saying that permission denied. Would please help advise? Thank you. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.
> -- Denes Turei, Ph.D. postdoc @ Saez Lab, Uni Heidelberg & Uniklinik RWTH Aachen & EMBL Heidelberg +4915166299976 Germany denes.turei@embl.de http://www.ebi.ac.uk/~denes public key: http://pgp.mit.edu:11371/pks/lookup?op=get&search=0x5706A4B609DD65A6 for accessing papers use Sci-Hub: http://sci-hub.tw/

No problem take your time please. Thank you for advice Denes.

Cheers,

**Comment by Nic-Nic** [comment]
Fixed in https://github.com/saezlab/Omnipath_Cytoscape/pull/1
