### ISSUE TITLE
Difference between pa.load_omnipath() and pa.init_network(pypath.data_formats.pathway)?

### ISSUE THREAD

**Issue by jadeshi** [saezlab/pypath#69]
These commands are presented in the first sections of the pypath tutorial:

http://pypath.omnipathdb.org/notebooks/pypath_build_networks.html

and I'm just wondering what the difference between these two commands are. I'm asking between I noticed the graphs they produce are different sizes. The first command creates a larger graph with roughly twice the number of nodes, but they both seem to be querying the entire OmniPath database:

Graph 1: IGRAPH UN-T 8947 34074 -- unnamed
Graph 2: IGRAPH UN-T 4788 14703 -- unnamed

Therefore I'm a bit confused at what the difference between them is. Could someone please clarify this for me? Thanks!

**Comment by deeenes** [comment]
Hi,

In `pypath.data_formats` you find network data input definitions grouped in dicts. For example `pathway` contains the activity flow resources. `pa.init_network(pypath.data_formats.pathway)` loads only the ones in this dict.

The `load_omnipath` method loads the networks from the `pathway`, `ptm` (enzyme-substrate databases) and `interaction` (databases without direction but with literature references) categories and after uses some additional resources to set further directions and effect signs, then removes the undirected interactions with only one literature reference or only supported by papers describing more than one interaction.

This procedure is similar to the way how we built the network in the 2016 paper, finding a balance between coverage and quality.

Overall, I suggest to look at the input sets in the `data_formats` module (for example `data_formats.pathway.keys()` and decide yourself which databases you want to use.
To get directions from additional resources you can call `pa.third_source_directions()` and to remove interactions supported only by papers describing many interactions you can call `pa.remove_htp(threshold = 10, keep_directed = True)`, or to remove undirected interactions `pa.remove_undirected()`. 

I hope this helps, please ask if you have further questions.

Best,

Denes

**Comment by deeenes** [comment]
I hope this question has been answered, I am closing the issue.
