### ISSUE TITLE
PTMs for rat

### ISSUE THREAD

**Issue by Nic-Nic** [saezlab/pypath#71]
I just tried to load the PTM network for rat using pypath but results in a network with 0 nodes and 0 interactions. What I did is:

```Python
pa = pypath.PyPath(ncbi_tax_id=10116)
pa.init_network(pypath.data_formats.ptm_all)
```

which after some ¨processing¨ gives this:

```Python
	### ERROR ###### Missing reference list for protein (default name type:
	uniprot), in taxon 10116
	Missing reference list for protein (default name type: uniprot), in taxon 10116

 > 0 interactions between 0 nodes
 from 0 resources have been loaded,
 for details see the log: ./log/k58ir.log
```

:(

**Comment by deeenes** [comment]
Network resources are not supposed to work with different organisms yet. Instead one can load the human network and translate:

```
pa = pypath.PyPath()
pa.init_network(pypath.data_formats.ptm_all)
pa.orthology_translation(10116)
```

**Comment by deeenes** [comment]
This will be resolved by the new reader module I think.

**Comment by deeenes** [comment]
But if you want enzyme-substrate interactions, the `pypath.ptm.PtmAggregator` is able to load directly or by homology interactions of non-human organisms.

**Comment by Nic-Nic** [comment]
Great, thanks :)
