### ISSUE TITLE
Add Dockerfile

### ISSUE THREAD

**Issue by cthoyt** [saezlab/pypath#73]
A Dockerfile would be really useful to provide so the entire database could be built from scratch (all dependencies, resources, etc.)

**Comment by ntung** [comment]
In my experience, it is challenging to install pypath. We have some interns who are neither computer science students nor software engineers and are doing to figure out pypath. They always need our help. A docker image would be worth for any developers.

**Comment by ivanovaos** [comment]
Hi @ntung, we are currently working on it. The docker image will be provided soon. In the meantime, can you maybe provide your usual setup (OS, python version, etc.)?

**Comment by deeenes** [comment]
> In my experience, it is really challenging to install pypath. 

Since we recently removed `igraph` and hence `cairo` from the mandatory dependencies it's not so challenging any more. I think on any operating system one can simply do `pip install git+git://github.com/saezlab/pypath.git`

**Comment by Nic-Nic** [comment]
Closing as solved
