### ISSUE TITLE
CellPhoneDB and annot module

### ISSUE THREAD

**Issue by Nic-Nic** [saezlab/pypath#75]
There seems to be some kind of bug when loading the annotation table. Seems to be only for the CellPhoneDB resource.

To reproduce:

```python
from pypath import annot
a = annot.AnnotationTable(keep_annotators=True)
a.load()
a.to_dataframe()
```

Which raises:

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-19-100b4db749d6> in <module>()
----> 1 a.to_dataframe()

~/.local/lib/python3.6/site-packages/pypath/annot.py in to_dataframe(self)
   1012     def to_dataframe(self):
   1013 
-> 1014         colnames = ['__'.join(name) for name in self.names]
   1015 
   1016         df = pd.DataFrame(

~/.local/lib/python3.6/site-packages/pypath/annot.py in <listcomp>(.0)
   1012     def to_dataframe(self):
   1013 
-> 1014         colnames = ['__'.join(name) for name in self.names]
   1015 
   1016         df = pd.DataFrame(

TypeError: sequence item 2: expected str instance, bool found
```

Checking further, seems that `a.names` contains some unexpected elements for the last annotations from CellPhoneDB, some examples:
* `('CellPhoneDB', 'https://www.ncbi.nlm.nih.gov/pubmed/22505611')`
* `('CellPhoneDB', 'Artipical_chemokine_receptor_add', False)` <- raises `TypeError` from here
* `('CellPhoneDB', 'Atipical_chemokine_receptor_add', False)`
* `('CellPhoneDB', 'Atipical_chemokine_receptor_add', True)`

and so on so forth...

**Comment by deeenes** [comment]
Fixed in aad90b0
