### ISSUE TITLE
Prioritizing log messages

### ISSUE THREAD

**Issue by deeenes** [saezlab/pypath#77]
At the momet the log is too verbose. A verbosity level should be assigned to each log message, which is the second argument of the `_log` method, e.g. `self._log('message', 1)`. The default log level is 0, if something is not important we should give a higher value, if something must be printed also to the console, I used to give -9.

**Comment by Nic-Nic** [comment]
Already implemented, closing

**Comment by deeenes** [comment]
I meant to add a verbosity number for each `._log()` call. We haven't done it yet :)

**Comment by Nic-Nic** [comment]
oops sorry

**Comment by Nic-Nic** [comment]
Is this still relevant/needed to implement? If not, should close

**Comment by deeenes** [comment]
Yes, it would be great to set priorities for log messages, so there would be an option to output a reasonable amount of useful information to the console. Though OmniPath has about 150-200 todo items, and these issues are only a small part of it – we can close this issue as it's not really useful in our work organization.
