### ISSUE TITLE
'Deacetylation' vs. 'deacetylation' in PTM data

### ISSUE THREAD

**Issue by johnbachman** [saezlab/pypath#8]
Hi, thanks for this resource. Just letting you know that in the PTM data as retrieved by the web service, there is one inconsistent entry for a deacetylation event, where the modification type is capitalized as 'Deacetylation'

This API query

```http://omnipathdb.org/ptms/Q96EB6?format=json```

yields a list of modifications which includes

```{"residue_type": "K", "modification": "Deacetylation", "substrate": "Q04206", "residue_offset": 310, "enzyme": "Q96EB6"}```

**Comment by deeenes** [comment]
Thanks John for spotting this, fixed in pypath (v0.7.54). For the webservice I need to update the data on the server, will do in the next few days.
