### ISSUE TITLE
pypath.annot.AnnotationTable.todataframe()

### ISSUE THREAD

**Issue by Nic-Nic** [saezlab/pypath#82]
Hi Dénes,

I was trying to generatethe dataframe of the complete set of annotations but came up to this:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-15-78c88651627b> in <module>
----> 1 df = a.to_dataframe()

~/.local/lib/python3.7/site-packages/pypath/annot.py in to_dataframe(self)
   1630     def to_dataframe(self):
   1631 
-> 1632         colnames = ['__'.join(name) for name in self.names]
   1633 
   1634         df = pd.DataFrame(

~/.local/lib/python3.7/site-packages/pypath/annot.py in <listcomp>(.0)
   1630     def to_dataframe(self):
   1631 
-> 1632         colnames = ['__'.join(name) for name in self.names]
   1633 
   1634         df = pd.DataFrame(

TypeError: sequence item 3: expected str instance, int found
```

I was checking and apparently some of the names contain integers. For instance I saw that many (repeated) entries from TopDB have this issue (e.g. TopDB_Bacterial_inner_membrane_Signal 99, TopDB_Bacterial_inner_membrane_Signal 100, and so on). Is that expected or there's something going on here?

**Comment by deeenes** [comment]
Because we create a boolean array and if certain factors have only a few levels, those should form columns in this array; but numbers definitely not. This should fix: 3665242
