### ISSUE TITLE
How to get list of references for each graph edge?

### ISSUE THREAD

**Issue by jadeshi** [saezlab/pypath#86]
Hey, just wondering what the best way is to get the list of references for a particular edge of an interaction graph. Specifically, after defining a new PyPath instance and loading some resources:

**pa = pypath.PyPath()
pa.load_resources({'signor':pypath.data_formats.pathway['signor']})**

I'm interested in proteins that KRAS activates. I can get a list of these by following the tutorial:
**list(pa.gs_stimulates('KRAS').gs())**

gives the following list:
**[u'MAP3K1',
 u'PIK3CD',
 u'RAF1',
 u'PIK3CG',
 u'TCF3',
 u'RASSF1',
 u'PIK3CB',
 u'PIK3CA',
 u'BRAF']**

But would it also be possible to get a list of all the literature references for each of these connections? Thanks!

**Comment by deeenes** [comment]
Hi Jade,

Starting from your approach you could do something like this:

```
import itertools
from pypath import main, data_formats

pa = main.PyPath()
pa.init_network(data_formats.pathway)

vid_kras_stimulators = list(pa.gs_stimulates('KRAS').ids())

vid_kras = pa.dgenesymbol('KRAS').index

eids = pa.dgraph.get_eids(
    itertools.product(
        (vid_kras,),
        vid_kras_stimulators
    )
)

result = []

for eid in eids:
    edge = pa.dgraph.es[eid]
    uniprots = (
        pa.dgraph.vs[edge.source]['name'],
        pa.dgraph.vs[edge.target]['name'],
    )
    genesymbols = (
        pa.dgraph.vs[edge.source]['label'],
        pa.dgraph.vs[edge.target]['label'],
    )
    references = tuple(ref.pmid for ref in edge['refs_by_dir'][uniprots])
    sources = edge['dirs'].sources[uniprots]
    is_stimulation = edge['dirs'].is_stimulation(uniprots)
    is_inhibition = edge['dirs'].is_inhibition(uniprots)
    result.append([
        uniprots,
        genesymbols,
        references,
        sources,
        is_stimulation,
        is_inhibition,
    ])
```

Be aware, the undirected and directed graphs are different objects, their vertex and edge IDs are different.

Indeed would be nice to have a more convenient method for this, we may add some soon.
Also soon the graph will be stored in data frames instead of an igraph object and hopefully it will make it easier to query.

Best,

Denes

**Comment by deeenes** [comment]
To illustrate the latter, we recently introduced a data frame for the network:

```
from pypath import network, mapping

kras_uniprot = mapping.map_name0('KRAS', 'genesymbol', 'uniprot')

net = network.Network.from_igraph(pa)

kras_stimulates = net.records[
    (net.records.id_a == kras_uniprot) &
    (net.records.effect == 1)
][['id_a', 'id_b', 'sources', 'references']]
```

**Comment by jadeshi** [comment]
Awesome, this is exactly what I needed. Thanks so much for the quick reply!
