### ISSUE TITLE
PtmAggregator obj contain empty enz_sub 

### ISSUE THREAD

**Issue by luli7** [saezlab/pypath#91]
Dear Denes,

Thank you for updating the tutorial pypath.omnipathdb.org/notebooks/pypath_guide.html

For the section "Enzyme-substrate interactions", after loading ptm_db by ptm.PtmAggregator(), the enz_sub dictionary is empty. Therefore when running ptm_db.enz_sub[('Q13177','P01236')][0], I got keyError.

I am currently using pypath 0.8.18 under python3.6 on Ubuntu 18.04.

Thank you very much for your help.
Best regards
Lu

**Comment by deeenes** [comment]
Probably same as #93, due to failed downloads. I will also test this with an empty cache.

**Comment by deeenes** [comment]
With dd683c8 `ptm.PtmAggregator` loaded from empty cache successfully, using my home internet connection.
Me too I got errors when attempted to load it with a not-so-good connection, particularly with FTP sites of UniProt and NCBI. In the preceding commits I've done a couple of minor modifications on `pypath.curl` for better reliability with slow connections. Finally these resolved the issue.
