### ISSUE TITLE
loading annotation

### ISSUE THREAD

**Issue by luli7** [saezlab/pypath#92]
Hi Everyone,

I am using pypath 0.8.18 with Python3.6 on Ubuntu 18.04.
I tried to load annotation from pypath.annot.AnnotationTable() and get  following error message:
  File "/usr/lib/python3.6/zipfile.py", line 1198, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file.

I also tried to  retrieve annotation from specific databases, as listed in section 15 of tutorial "pypath.omnipathdb.org/notebooks/pypath_guide.html", and got: 
  File "/home/luli7/.local/lib/python3.6/site-packages/pypath/dataio.py", line 7192, in signor_pathways
    'select', {'name': 'pathway_list'}
AttributeError: 'NoneType' object has no attribute 'findAll'

Thank you for your help or suggestions.
Best regards
Lu

**Comment by luli7** [comment]
Hi,
I cleaned .cache, then load the above again. after more than one hour running, I got a different error message:
  File "/home/luli7/.local/lib/python3.6/site-packages/pypath/dataio.py", line 2246, in comppi_locations
    for iloc in comppi_interaction_locations(organism = organism):
  File "/home/luli7/.local/lib/python3.6/site-packages/pypath/dataio.py", line 2221, in comppi_interaction_locations
    _ = next(c.result)
TypeError: 'NoneType' object is not an iterator

so may be this time, it is related to retrieve annotation from comPPI?

I also checked log file, the last few lines are:
[2019-06-13 16:06:16] [annot] Inferring complex annotations from `Vesiclepedia`.
[2019-06-13 16:06:17] [annot] Loading annotations from `SignaLink3`.
[2019-06-13 16:06:17] [annot] Loading data from `SignaLink3`.
[2019-06-13 16:06:17] [annot] Processing data from `SignaLink3`.
[2019-06-13 16:06:17] [annot] Inferring complex annotations from `SignaLink3`.
[2019-06-13 16:06:18] [annot] Loading annotations from `ComPPI`.
[2019-06-13 16:06:18] [annot] Loading data from `ComPPI`.
[2019-06-13 16:06:18] [curl] Creating Curl object to retrieve data from `http://comppi.linkgroup.hu/downloads`
[2019-06-13 16:06:18] [curl] Cache file path: `/home/luli7/.pypath/cache/957cb95083d12d486305f6896a541842-downloads`
[2019-06-13 16:06:18] [curl] POST parameters set: fDlSet=comp&fDlSpec=0&fDlMLoc=all&fDlSubmit=Download
[2019-06-13 16:06:18] [curl] Setting up and calling pycurl.
[2019-06-13 16:10:42] [mapping] Removing mapping table `entrez` to `uniprot` for organism `9606`.
[2019-06-13 16:11:22] [mapping] Removing mapping table `uniprot-sec` to `uniprot-pri` for organism `9606`.
[2019-06-13 16:11:22] [mapping] Removing mapping table `trembl` to `genesymbol` for organism `9606`.
[2019-06-13 16:11:22] [mapping] Removing mapping table `genesymbol5` to `uniprot` for organism `9606`.
[2019-06-13 16:11:22] [mapping] Removing mapping table `genesymbol` to `uniprot` for organism `9606`.
[2019-06-13 16:11:22] [mapping] Removing mapping table `genesymbol-syn` to `uniprot` for organism `9606`

I tried to connect http://comppi.linkgroup.hu/downloads, and it seems this link is not active.

Thank you for your help.
Best regards
Lu

**Comment by luli7** [comment]
Hi,
I have tested almost all the annotation databases based on annot.py.
The commented one (labelled with "#") is the one currently I can not retrieve anything.

a=annot.AnnotationTable(
	protein_sources=(
    #'Membranome',
    #'Exocarta',
    'Vesiclepedia',
    #'Matrisome',
    'Surfaceome',
    #'CellSurfaceProteinAtlas',
    'HumanPlasmaMembraneReceptome',
    #'Matrixdb',
    #'Locate',
    #'GOIntercell',
    'CellPhoneDB',
    #'Ramilowski2015',
    #'Ramilowski2015Location',
    #'Kirouac2010',
    'GuideToPharmacology',
    #'Adhesome',
    #'Integrins',
    #'Opm',
    'Topdb',
    #'Hgnc',
    'Zhong2015',
    #'HumanProteinAtlas',
    #'Comppi',
    'SignorPathways',
    'SignalinkPathways',
    'KeggPathways',
    'NetpathPathways',
    #'Cpad',
	'CorumGO',
	'CellPhoneDBComplex',
	'CorumFuncat',
	'HpmrComplex',
)
)

As pypath dynamically retrieving information from different resources, would it be possible to produce a resource table to show which one is active or not active...

Thank you for your help
Best regards
Lu

**Comment by deeenes** [comment]
Hi Lu,

Thaks a lot for your efforts with testing and reporting these issues.
Me too I see recently the ComPPI server is down.
This high number of failed resources is unusual and your other issues also likely due to failed downloads. Have you run these tests with good quality network connection? The resources in the `annot` module I downloaded myself over the past weeks, hence it's surprising so many of them failed. I will now test it with an empty cache (however I am on holidays and I can use only my home connection).

Best,

Denes

**Comment by deeenes** [comment]
Here I added an exception handling to avoid complete build failures if 1-2 resources fall out: dde93a8
However now I built tha annotation database from empty cache and 28 out of the 29 resources loaded without error. Only ComPPI is missing, obviously because it has a server outage.

**Comment by luli7** [comment]
Hi Denes,

Thank you very much for prompt reply and help.
I confirm after upgrading to pypath 0.8.20, I can load almost all the annotations except ComPPI.
I have a quick question, I have noticed "Locate" and "Kirouac2010" in annot.py for protein_sources. But after loading them separately, it seems they are just combination of 'CellPhoneDB_complex', 'CORUM_GO', 'HPMR_complex', 'CORUM_Funcat' ?

Thank you  very much again for your help.
Best regards
Lu

**Comment by deeenes** [comment]
Hi Lu,

Sounds great! :)

Locate and Kirouac are completely different resources than the other 4 you mention. The latter 4 are the resources with annotations for complexes. For complexes we also infer annotations from other resources, e.g. if all components are receptors according to Kirouac then the complex is a receptor.

Best,

Denes

**Comment by luli7** [comment]
Hi Denes,

Thank you for your answer,
The reason I ask above question (related by Locate and Kirouac) is first of all, after loading a=annot.AnnotationTable(),  I did not find these two in a.annots.keys(). Then I load these two in a test annotation variable, test=annot.AnnotationTable(protein_sources=('Locate','Kirouac2010',)). Then I did test.annots.keys() and it returned ['CellPhoneDB_complex', 'CORUM_GO', 'HPMR_complex', 'CORUM_Funcat']). So I thought Locate and Kirouac are just combined annotation from the four databases.

Another related question is:  is there a way I can know what are the database resources included when I run pa.load_omnipath(), does Dorothea (TF regulons) included? What are the default database for omnipath so far?

Thank you very much for your help.

Best regards
Lu

**Comment by deeenes** [comment]
The `AnnotationTable` loads also the resources in `annot.complex_sources_default`. The `Locate` and `Kirouac2010` should not be missing, I see these could not load for me too, I will check why.

When you use `load_omnipath`, the resources in `data_formats.omnipath` will be loaded. You can add other resources by the `enzyme_substrate_extra`, the `ligand_receptor_extra` and the `pathway_extra` arguments. These will load additional interactions without literature references.

**Comment by deeenes** [comment]
aaad7b5 fixed the issue with Kirouac2010

**Comment by deeenes** [comment]
The server of Locate (locate.imb.uq.edu.au) is apparently down

**Comment by luli7** [comment]
Dear Denes,

Thank you very much.
Sorry to make this thread so long. But  I have a few more questions, relating to databases included in Omnipath. 

Based on your answer, and the tutorial section 5a (http://pypath.omnipathdb.org/notebooks/pypath_guide.html). I understand Omnipath is the collection of data_formats.pathway, data_formats.ptm, data_formats.ligand_receptor (the literature referenced ones), and  data_formats.interaction.

The pathway_extra is equal to data_formats.pathway_noref; enzyme_substrate_extra is equal to data-formats.ptm_noref and ligand_receptor_extra is equal to data_formats.ligand_receptor (the no literature reference ones).

So by default, in Omnipath, there is no transcription regulation from DoRothEA, nor miRNA, IncRNA data. There is also no pathwaycommons. Am I right?

Finally, what are the databases for data_formats.reaction? Is Reactome here or anywhere? and why you mention in section 5a, that this does not gauretee to work? What is the difference between reaction and ptm?

Sorry for so many questions and thank you very much for your patience.
Best regards
Lu

**Comment by luli7** [comment]
Hi Denes,
After another pypath update, it seems I can not load annotation again.
I have tried various internet connections at home and work.
Error message as following: 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luli7/.local/lib/python3.6/site-packages/pypath/annot.py", line 2137, in __init__
    self.load()
  File "/home/luli7/.local/lib/python3.6/site-packages/pypath/annot.py", line 2160, in load
    self.load_protein_resources()
  File "/home/luli7/.local/lib/python3.6/site-packages/pypath/annot.py", line 2291, in load_protein_resources
    self._load_resources(self.protein_sources, self.proteins)
  File "/home/luli7/.local/lib/python3.6/site-packages/pypath/annot.py", line 2301, in _load_resources
    for cls in definitions:
TypeError: 'NoneType' object is not iterable

Thank you very much for your help.
Best regards
Lu

**Comment by deeenes** [comment]
Sorry, my bad. I quickly modified this code yesterday and wrote `is None` instead of `is not None`. Fixed in a8a56c0
